{
 "title": "Nodes",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "$node / Uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{nodename=~\"$node\"} - node_boot_time_seconds{nodename=~\"$node\"}",
       "legendFormat": "{{ nodename }}"
      }
     ]
    }
   ]
  },
  {
   "title": "$node / Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load 1",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (nodename) (node_load1{nodename=~\"$node\"}) / count by (nodename) (rate(node_cpu_seconds_total{nodename=~\"$node\",mode=\"idle\"}[$interval]))",
       "legendFormat": "{{ nodename }}"
      }
     ]
    },
    {
     "title": "Load 5",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (nodename) (node_load5{nodename=~\"$node\"}) / count by (nodename) (rate(node_cpu_seconds_total{nodename=~\"$node\",mode=\"idle\"}[$interval]))",
       "legendFormat": "{{ nodename }}"
      }
     ]
    },
    {
     "title": "Load 15",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (nodename) (node_load15{nodename=~\"$node\"}) / count by (nodename) (rate(node_cpu_seconds_total{nodename=~\"$node\",mode=\"idle\"}[$interval]))",
       "legendFormat": "{{ nodename }}"
      }
     ]
    }
   ]
  },
  { "title": "$node / Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (nodename) (irate(node_cpu_seconds_total{nodename=~\"$node\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "Usage – {{ nodename }}"
    },
    {
     "expr": "avg by (nodename) (irate(node_cpu_seconds_total{nodename=~\"$node\",mode=\"iowait\"}[$interval])) * 100",
     "legendFormat": "IOwait – {{ nodename }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - ((node_memory_MemFree_bytes{nodename=~\"$node\"} + node_memory_Cached_bytes{nodename=~\"$node\"} + node_memory_Buffers_bytes{nodename=~\"$node\"}) / node_memory_MemTotal_bytes{nodename=~\"$node\"}))",
     "legendFormat": "Actual – {{ nodename }}"
    },
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{nodename=~\"$node\"}[$interval]) + avg_over_time(node_memory_Cached_bytes{nodename=~\"$node\"}[$interval]) + avg_over_time(node_memory_Buffers_bytes{nodename=~\"$node\"}[$interval])) / avg_over_time(node_memory_MemTotal_bytes{nodename=~\"$node\"}[$interval])))",
     "legendFormat": "Average – {{ nodename }}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_procs_running{nodename=~\"$node\"}",
     "legendFormat": "Running – {{ nodename }}"
    },
    {
     "expr": "node_procs_blocked{nodename=~\"$node\"}",
     "legendFormat": "Blocked by I/O – {{ nodename }}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (nodename) (node_hwmon_temp_celsius{nodename=~\"$node\"})",
     "legendFormat": "Actual – {{ nodename }}"
    },
    {
     "expr": "avg by (nodename) (avg_over_time(node_hwmon_temp_celsius{nodename=~\"$node\"}[$interval]))",
     "legendFormat": "Average – {{ nodename }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{nodename=~\"$node\",mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{nodename=~\"$node\",mountpoint=\"/\"})",
     "legendFormat": "Root – {{ nodename }}"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{nodename=~\"$node\",mountpoint=\"/var/log\"} * 100) / node_filesystem_size_bytes{nodename=~\"$node\",mountpoint=\"/var/log\"})",
     "legendFormat": "Logs – {{ nodename }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (nodename, device) (rate(node_network_receive_bytes_total{nodename=~\"$node\",device=~\"eth0|tailscale0\"}[$interval])) * 8",
     "legendFormat": "{{ device }}-in – {{ nodename }}"
    },
    {
     "expr": "sum by (nodename, device) (rate(node_network_transmit_bytes_total{nodename=~\"$node\",device=~\"eth0|tailscale0\"}[$interval])) * 8",
     "legendFormat": "{{ device }}-out – {{ nodename }}"
    }
   ]
  },
  {
   "title": "Network Successful Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (nodename, device) (rate(node_network_receive_packets_total{nodename=~\"$node\",device=~\"eth0|tailscale0\"}[$interval]))",
     "legendFormat": "{{ device }}-in – {{ nodename }}"
    },
    {
     "expr": "sum by (nodename, device) (rate(node_network_transmit_packets_total{nodename=~\"$node\",device=~\"eth0|tailscale0\"}[$interval]))",
     "legendFormat": "{{ device }}-out – {{ nodename }}"
    }
   ]
  },
  {
   "title": "Network Dropped Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (nodename, device) (rate(node_network_receive_drop_total{nodename=~\"$node\",device=~\"eth0|tailscale0\"}[$interval]))",
     "legendFormat": "{{ device }}-in – {{ nodename }}"
    },
    {
     "expr": "sum by (nodename, device) (rate(node_network_transmit_drop_total{nodename=~\"$node\",device=~\"eth0|tailscale0\"}[$interval]))",
     "legendFormat": "{{ device }}-out – {{ nodename }}"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "unpoller_device_port_poe_watts{port_name=\"Coruscant\"}",
     "legendFormat": "{{port_name}}"
    },
    {
     "expr": "unpoller_device_port_poe_watts{port_name=\"Kashyyyk\"}",
     "legendFormat": "{{port_name}}"
    },
    {
     "expr": "unpoller_device_port_poe_watts{port_name=\"Alderaan\"}",
     "legendFormat": "{{port_name}}"
    },
    {
     "expr": "unpoller_device_port_poe_watts{port_name=\"Dathomir\"}",
     "legendFormat": "{{port_name}}"
    },
    {
     "expr": "unpoller_device_port_poe_watts{port_name=\"Mustafar\"}",
     "legendFormat": "{{port_name}}"
    }
   ]
  }
 ]
}