---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=github-releases depName=cert-metallb/metallb-operator
  - https://raw.githubusercontent.com/metallb/metallb-operator/refs/tags/v0.14.2/bin/metallb-operator.yaml
