---
# cert-manager release
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m0s
  chart:
    spec:
      chart: cert-manager
      version: "v1.17.0"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    image:
      tag: 'v1.16.0'
    crds:
      enabled: false
    extraEnv:
      - name: TZ
        value: ${TIMEZONE}
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
