---
# cert-manager release
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m0s
  chart:
    spec:
      chart: cert-manager
      version: "1.15.x"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    crds:
      enabled: true
    extraEnv:
      - name: TZ
        value: ${TIMEZONE}
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
