---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: garage-ui.${DOMAIN}
  namespace: nas
spec:
  secretName: garage-ui.${DOMAIN}
  dnsNames:
    - garage-ui.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
