---
# traefik release
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: headlamp
      version: "0.28.0"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
      interval: 12h
  values:
    config:
      oidc:
        clientID: ${HEADLAMP_GIHUB_CLIENTID}
        clientSecret: ${HEADLAMP_GITHUB_CLIENTSECRET}
        issuerURL: "https://github.com"
        scopes: "openid profile email"
