---
resources:
  - esphome-pvc.yaml
  - ../../../base/home-automation/esphome/release.yaml
  - certificate.yaml
  - ingress-route.yaml

patches:
  - path: values.yaml
    target:
      kind: HelmRelease
