---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headlamp.${DOMAIN}
  namespace: kube-system
spec:
  secretName: headlamp.${DOMAIN}
  dnsNames:
    - headlamp.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
