---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: kube-system
spec:
  values:
    image:
      # -- Container image registry
      registry: ghcr.io
      # -- Container image name
      repository: headlamp-k8s/headlamp
      # -- Image pull policy. One of Always, Never, IfNotPresent
      pullPolicy: IfNotPresent
      # -- Container image tag, If "" uses appVersion in Chart.yaml
      tag: "v0.40.1"
    initContainers:
      # - name: create-plugins-dir
      #   command:
      #     - /bin/sh
      #     - "-c"
      #     - |
      #       mkdir -p /home/headlamp/.config/Headlamp/plugins
      #       chown 100:101 home/headlamp/.config/Headlamp/plugins
      #   image: alpine:3.19
      #   securityContext:
      #     runAsUser: 0
      #     runAsGroup: 0
      #   volumeMounts:
      #     - mountPath: /home/headlamp/.config/Headlamp
      #       name: headlamp
      #       readOnly: false
      - name: create-kubeconfig
        command:
          - /bin/sh
          - "-c"
          - |
            kubectl config set-cluster PROD-KHC --server=https://kubernetes.default.svc --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            kubectl config set-credentials PROD-KHC --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
            kubectl config set-context PROD-KHC --cluster=PROD-KHC --user=PROD-KHC
            kubectl config use-context PROD-KHC
        env:
          - name: KUBERNETES_SERVICE_HOST
            fieldRef:
                fieldPath: status.hostIP
          - name: KUBERNETES_SERVICE_PORT
            value: "6443"
          - name: KUBECONFIG
            value: /home/headlamp/.config/Headlamp/kubeconfigs/config
        image: alpine/kubectl:1.35.2
        securityContext:
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 101
          runAsNonRoot: true
          runAsUser: 100
        volumeMounts:
          - mountPath: /home/headlamp/.config/Headlamp/kubeconfigs
            name: kubeconfig
            readOnly: false

    config:
      watchPlugins: true  # Set to true to enable automatic plugin updates in main headlamp container
      oidc:
        clientID: ${HEADLAMP_POCKETID_CLIENTID}
        clientSecret: ${HEADLAMP_POCKETID_CLIENTSECRET}
        issuerURL: ${HEADLAMP_POCKETID_ISSUERURL}
        scopes: "email,profile"
    volumeMounts:
      - mountPath: "/home/headlamp/.config/Headlamp/kubeconfigs/"
        name: kubeconfig
        readOnly: true
      - mountPath: "/home/headlamp/.config/Headlamp/"
        name: headlamp
        readOnly: false
    volumes:
      - name: kubeconfig
        emptyDir: {}
      - name: headlamp
        emptyDir: {}

    pluginsManager:
      enabled: true
      configContent: |
        plugins:
          - name: cert-manager
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_cert-manager
            version: 0.1.0
          - name: flux
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_flux
            version: 0.5.0
        installOptions:
          parallel: true
          maxConcurrent: 2
      baseImage: node:lts-alpine
