---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gotify.${DOMAIN}
  namespace: gotify
spec:
  secretName: gotify.${DOMAIN}
  dnsNames:
    - gotify.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
