---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  chart:
    spec:
      chart: home-assistant
      version: '13.4.2'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: '2024.11.0'

    imagePullSecrets:
      - name: github-registry

    env:
      - name: TZ
        value: ${TIMEZONE}

    # needed for homekit, wake-on-lan and ps4 integrations
    # hostNetwork: true

    # needed as workaround for dns issues with host network
    # dnsPolicy: ClusterFirst

    # needed for zigbee usb access
    securityContext:
      privileged: true

    persistence:
      config:
        enabled: true
        size: 1Gi
        storageClass: longhorn
        type: pvc
        accessMode: ReadWriteMany
        # hostPath: ${PATH_HOME}/home-assistant
        mountPath: /config
    metrics:
      enabled: true
      prometheusRule:
        enabled: true

  interval: 10m0s
