---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        # pod:
        #   securityContext:
        #     privileged: true
        pod:
          securityContext:
            # runAsUser: 65534
            # runAsGroup: 65533
            runAsNonRoot: false
            # fsGroup: 65533
            # fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2025.9.3
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.103.2
            args:
              [
                "--auth",
                "none",
                "--disable-telemetry",
                "--disable-update-check",
                "--user-data-dir",
                "/config/.vscode",
                "--extensions-dir",
                "/config/.vscode",
                "--port",
                "8080",
                "/config"
              ]
            env:
              TZ: "${TIMEZONE}"

    # service:
    #   # Configure a service for the main application
    #   main:
    #     controller: main
    #     type: ClusterIP
    #     ports:
    #       http:
    #         port: 8123
    #   # Configure a service for the code-server sidecar
    #   code:
    #     type: ClusterIP
    #     controller: main
    #     ports:
    #       http:
    #         port: 8081
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 8123
          code-server:
            port: 8080

    metrics:
      enabled: true
      prometheusRule:
        enabled: true
