---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich.${DOMAIN}
  namespace: media
spec:
  secretName: immich.${DOMAIN}
  dnsNames:
    - ${HOST_IMMICH}.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
