---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich
  namespace: media
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: "https://${HOST_IMMICH}.${DOMAIN}"
    gethomepage.dev/description: "Self-hosted photo and video management solution"
    gethomepage.dev/group: Media
    gethomepage.dev/icon: immich.png
    gethomepage.dev/app: immich-server  # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: "Immich"
spec:
  entryPoints:
    - websecure
  tls:
    secretName: immich.${DOMAIN}
  routes:
    - kind: Rule
      match: Host(`${HOST_IMMICH}.${DOMAIN}`)
      services:
        - name: immich-server
          kind: Service
          namespace: media
          port: 2283
