---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  interval: 10m
  values:
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: mosquitto-pvc
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/config
              - path: /mosquitto/data
              - path: /mosquitto/log
    service:
      app:
        controller: mosquitto
        type: ClusterIP
        ports:
          mqtt:
            port: 1883
          websocket:
            port: 9001
