---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: victorialogs.${DOMAIN}
  namespace: monitoring
spec:
  secretName: victorialogs.${DOMAIN}
  dnsNames:
    - ${HOST_VICTORIALOGS}.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
