---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vm-logs
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: victoria-logs-single
      # renovate: registryUrl=https://victoriametrics.github.io/helm-charts chart=victoria-logs-single
      version: 0.9.8
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  values:
    server:
      enabled: true

      persistentVolume:
        enabled: true
        accessModes:
          - ReadWriteOnce
        storageClass: "longhorn"
        existingClaim: ""
        size: 20Gi
