---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mqttui
  namespace: home-automation
spec:
  interval: 10m
  values:
    service:
      app:
        annotations:
          gatus.io/monitor: "true"
          gatus.home-operations.com/endpoint: |
            group: "home-automation"
            url: http://mqttui.home-automation.svc.cluster.local:5000/
            conditions:
              - "[STATUS] == 200"
              - "[RESPONSE_TIME] < 1000"
