---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-upgrade
resources:
  - github.com/rancher/system-upgrade-controller
images:
  - name: rancher/system-upgrade-controller
    newTag: v0.17.0
patchesStrategicMerge:
  - ./system-upgrade-patches.yaml
