---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      pocket-id:
        containers:
          app:
            image:
              repository: ghcr.io/pocket-id/pocket-id
              tag: v2.5.0
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi

    service:
      app:
        controller: pocket-id
        ports:
          http:
            port: 1411
