---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: igotify
  namespace: gotify
spec:
  chart:
    spec:
      chart: igotify
      version: '1.0.3'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ghimele
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      # -- repository with igotify image
      repository: ghcr.io/androidseb25/igotify-notification-assist
      tag: "latest"

    imagePullSecrets: []

    service:
      type: ClusterIP
      port: 8080

    serviceAccount:
      # -- enable serviceAccount
      create: true
      # -- add annotations to serviceAccount
      annotations: {}
      # -- name of the serviceAccount (will be generated if empty)
      name: "igotify"

    persistence:
      # -- enable persistence when true
      enabled: false
      # -- default storage size
      size: 500Mi
      # -- accessMode
      accessMode: ReadWriteOnce
      # -- actual storageClass
      storageClass: ""

  interval: 10m0s
