---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vmetrics
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      # renovate: registryUrl=https://victoriametrics.github.io/helm-charts chart=victoria-metrics-k8s-stack
      version: 0.42.0
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    # Configures vmsingle params
    vmsingle:
      # -- VMSingle annotations
      annotations: {}
      # -- Create VMSingle CR
      enabled: true
      # -- Full spec for VMSingle CRD. Allowed values describe [here](https://docs.victoriametrics.com/operator/api#vmsinglespec)
      spec:
        port: "8429"
        # -- Data retention period. Possible units character: h(ours), d(ays), w(eeks), y(ears), if no unit character specified - month. The minimum retention period is 24h
        # See these [docs](https://docs.victoriametrics.com/single-server-victoriametrics/#retention)
        retentionPeriod: "1"
        replicaCount: 1
        extraArgs: {}
        storage:
          accessModes:
            - ReadWriteOnce
          storageClass: "longhorn"
          resources:
            requests:
              storage: 20Gi
    vmagent:
      # -- Create VMAgent CR
      enabled: true
      spec:
        port: "8429"
        selectAllByDefault: true
        scrapeInterval: 20s
        externalLabels: {}
        # For multi-cluster setups it is useful to use "cluster" label to identify the metrics source.
        # For example:
        cluster: KHC-PROD
        inlineScrapeConfig: |
          - job_name: unraid
            scheme: http
            scrape_interval: 60s
            static_configs:
              - targets: ['${HOST_OCEANO}.${DOMAIN}:9100']
          - job_name: pfsense
            scheme: http
            scrape_interval: 60s
            static_configs:
              - targets: ['${HOST_PFSENSE}.${DOMAIN}:9100']
          - job_name: "KHC-TEST"
            scrape_interval: 60s
            static_configs:
              - targets: ["test-node-exporter:9100"]

    # -- prometheus-node-exporter dependency chart configuration. For possible values check [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml)
    prometheus-node-exporter:
      enabled: true

      # all values for prometheus-node-exporter helm chart can be specified here
      service:
        # Add the 'node-exporter' label to be used by serviceMonitor to match standard common usage in rules and grafana dashboards
        labels:
          jobLabel: PROD-KHC
      extraArgs:
        - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
        - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|erofs|sysfs|tracefs)$
      # -- Node Exporter VM scrape config
      vmScrape:
        # whether we should create a service scrape resource for node-exporter
        enabled: true

        # -- [Scrape configuration](https://docs.victoriametrics.com/operator/api#vmservicescrapespec) for Node Exporter
        spec:
          jobLabel: jobLabel
          selector:
            matchLabels:
              app.kubernetes.io/name: '{{ include "prometheus-node-exporter.name" (index .Subcharts "prometheus-node-exporter") }}'
          endpoints:
            - port: metrics
              metricRelabelConfigs:
                - action: drop
                  source_labels: [mountpoint]
                  regex: "/var/lib/kubelet/pods.+"
