---

name: homelab-management

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_REMOTE_AGENT=$DOZZLE_REMOTE_AGENT
    ports:
      - $DOZZLE_PORT:8080
