---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: home-automation
spec:
  interval: 10m
  values:
    service:
      annotations:
        gatus.io/monitor: "true"
        gatus.home-operations.com/endpoint: |
          group: "home-automation"
          url: http://frigate.home-automation.svc.cluster.local:5000/
          conditions:
            - "[STATUS] == 200"
            - "[RESPONSE_TIME] < 2000"

    config: |
      mqtt:
        host: mosquitto.home-automation.svc.cluster.local
        port: 1883
        topic_prefix: frigate
        client_id: frigate

      detectors:
        cpu1:
          type: cpu

      go2rtc:
        streams:
          AdeleCamera: 
            - rtsp://{FRIGATE_CAM1_USER}:{FRIGATE_CAM1_PASS}@192.168.51.105:554/stream1
            - "ffmpeg:AdeleCamera#audio=opus"
        webrtc:
          candidates:
            - frigate.home-automation.svc.cluster.local:8555

      cameras:
        AdeleCamera:
          enabled: true
          ffmpeg:
            inputs:
              - path: 
                  rtsp://127.0.0.1:8554/AdeleCamera     # <----- The stream you want to use for record
                roles:
                  - record
              - path: 
                  rtsp://127.0.0.1:8554/AdeleCamera     # <----- The stream you want to use for record
                roles:
                  - detect
          audio:
            enabled: true
            two_way: true
          detect:
            enabled: false # <---- disable detection until you have a working camera feed
            width: 1280
            height: 720 
          motion:
            enabled: true   
            threshold: 30        # Increase to reduce sensitivity
            contour_area: 35     # Increase to require larger motion
          record:
            enabled: true
            retain:
              days: 7      
              mode: motion
      detect:
        enabled: false

    persistence:
      media:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: frigate-media
        storageClass: nfs-media
        subPath: /media/frigate
        accessMode: ReadWriteMany
        # -- Do not delete the pvc upon helm uninstall
        skipuninstall: false
    nodeSelector:
      node-role.kubernetes.io/nfs: ""
    env:
      FRIGATE_CAM1_USER: ${FRIGATE_CAM1_USER}
      FRIGATE_CAM1_PASS: ${FRIGATE_CAM1_PASS}
      FRIGATE_CAM1_IP: ${FRIGATE_CAM1_IP}
      FRIGATE_HOSTNAME: ${HOST_FRIGATE}.${DOMAIN}
