---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: home-automation
spec:
  interval: 10m
  values:
    config: |
      mqtt:
        host: mosquitto.home-automation.svc.cluster.local
        port: 1883
        topic_prefix: frigate
        client_id: frigate

      detectors:
        cpu1:
          type: cpu

      cameras:
        AdeleCamera:
          enabled: true
          ffmpeg:
            inputs:
              - path: 
                  rtsp://{FRIGATE_CAM1_USER}:{FRIGATE_CAM1_PASS}@${FRIGATE_CAM1_IP}:554/stream1     # <----- The stream you want to use for record
                roles:
                  - record
              - path: 
                  rtsp://{FRIGATE_CAM1_USER}:{FRIGATE_CAM1_PASS}@${FRIGATE_CAM1_IP}:554/stream2     # <----- The stream you want to use for record
                roles:
                  - detect
          detect:
            enabled: false # <---- disable detection until you have a working camera feed
            width: 1280
            height: 720 
          motion:
            enabled: true   
            threshold: 30        # Increase to reduce sensitivity
            contour_area: 30     # Increase to require larger motion
          record:
            enabled: true
            retain:
              days: 7      
              mode: motion
      detect:
        enabled: false

    persistence:
      media:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: frigate-media
        storageClass: nfs-media
        subPath: /media/frigate
        accessMode: ReadWriteMany
        # -- Do not delete the pvc upon helm uninstall
        skipuninstall: false
    nodeSelector:
      node-role.kubernetes.io/nfs: ""
    env:
      FRIGATE_CAM1_USER: ${FRIGATE_CAM1_USER}
      FRIGATE_CAM1_PASS: ${FRIGATE_CAM1_PASS}
      FRIGATE_CAM1_IP: ${FRIGATE_CAM1_IP}
