---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: home-automation
spec:
  interval: 10m
  values:
    persistence:
      recordings:
        type: persistentVolumeClaim
        existingClaim: frigate-recordings
        mountPath: /media/frigate/recordings
    nodeSelector:
      node-role.kubernetes.io/nfs: ""
