---
# flux HelmRepository for installing homepage
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 24h
  url: https://ghimele.github.io/helm-charts/
