---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard-prometheus
  namespace: monitoring
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: "https://${HOST_PROMETHEUS}.${DOMAIN}"
    gethomepage.dev/description: Metrics monitoring solution.
    gethomepage.dev/group: Monitoring
    gethomepage.dev/icon: prometheus.png
    gethomepage.dev/name: Prometheus
    gethomepage.dev/app: prometheus
    gethomepage.dev/widget.type: prometheus
    gethomepage.dev/widget.url: "https://${HOST_PROMETHEUS}.${DOMAIN}"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`${HOST_PROMETHEUS}.${DOMAIN}`)
      services:
        - kind: Service
          name: prometheus-operated
          namespace: monitoring
          port: 9090
  tls:
    secretName: prometheus.${DOMAIN}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard-alertmanager
  namespace: monitoring
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: "https://${HOST_ALERTS}.${DOMAIN}"
    gethomepage.dev/description: Alerts monitoring solution.
    gethomepage.dev/group: Monitoring
    gethomepage.dev/icon: prometheus.png
    gethomepage.dev/name: Alert Manager
    gethomepage.dev/app: alertmanager
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`${HOST_ALERTS}.${DOMAIN}`)
      services:
        - kind: Service
          name: alertmanager-operated
          namespace: monitoring
          port: 9093
  tls:
    secretName: alerts.${DOMAIN}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard-grafana
  namespace: monitoring
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: "https://${HOST_GRAFANA}.${DOMAIN}"
    gethomepage.dev/description: Monitoring Dashboards.
    gethomepage.dev/group: Monitoring
    gethomepage.dev/icon: grafana.png
    gethomepage.dev/name: Grafana
    gethomepage.dev/app: grafana
    gethomepage.dev/widget.type: grafana
    gethomepage.dev/widget.url: "https://${HOST_GRAFANA}.${DOMAIN}"
    gethomepage.dev/widget.username: ${GRAFANA_USERNAME}
    gethomepage.dev/widget.password: ${GRAFANA_PASSWORD}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`${HOST_GRAFANA}.${DOMAIN}`)
      services:
        - kind: Service
          name: grafana
          namespace: monitoring
          port: 80
  tls:
    secretName: grafana.${DOMAIN}
