---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: blakeblackshear
  namespace: flux-system
spec:
  type: oci
  interval: 30m
  url: oci://ghcr.io/blakeblackshear/charts
