---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8s-home-lab
  namespace: flux-system
spec:
  type: oci
  interval: 30m
  url: oci://ghcr.io/k8s-home-lab/helm-charts
