---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pocke-id
  namespace: flux-system
spec:
  type: default
  interval: 30m
  url: oci://ghcr.io/hobbit44/pocket-id-helm/pocket-id
