# secret to test if the encryption/decryption works with fluxcd.
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: home-assistant
stringData:
    HASS_SECRET_LATITUDE: ENC[AES256_GCM,data:/YdAKvdHrA62w5FH06TS0to=,iv:qAr4QStlqRiiwA0vtby5it64Hz3VSykzOXbMcKJkTYQ=,tag:9p7M+I++LWZP4JPln7HCRQ==,type:str]
    HASS_SECRET_LONGITUDE: ENC[AES256_GCM,data:BiA7MqV/15ChK7mBZNdF4SI=,iv:nsvu+sx5MEZzRgtRgpjGzb4oQGpju9VEhVcDaX++JaE=,tag:nRoWVAV12eNO11kXB8n1lA==,type:str]
    HASS_SECRET_ELEVATION: ENC[AES256_GCM,data:duZE,iv:s8Duly/sfS0z9bQDw0Vlt7STKRHPPU2g0K7KeE7JGOk=,tag:QxfR/m4f2K33ke/FbXY7wA==,type:str]
    HASS_RECORDER_DB_URL: ENC[AES256_GCM,data:7D/nnpftKrHiCdVUR78oBbCfxZAXhIiM4t6XXQAgtW+Ddw==,iv:DWCESBW4C5TURxVmZQrvcFBx2H1zohnTFbx2247teok=,tag:gI1Ju93080+7wjhMqXQexg==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:liDWtuHp1GQfS16s1EG7,iv:5hfXIWZ0z3CN06UdCAyk90vj9gFbrtk/FkuYWUfgkJg=,tag:COaGwajXOJn/Cw9Dp62s8Q==,type:str]
    TZ: ENC[AES256_GCM,data:XsnuE0ZjijzkSC75d8ar,iv:tl0vJBRA4Y7vSONZ6WZhjmrMPbWxVdozVIqaI+ZA9fM=,tag:xi7grA6PHargsEOABXey4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MkkwenRSNCtRQUtmQi9m
            RUVQZU1SMGRHYkVnZTZuRXdNcGRhd1pSamtnCjV1VmlaeENjU2hCU0JGM3V5ZGJr
            ZVJFTFRZZ2JwRU9IYWdhRkllWXptZGMKLS0tIFBRNjBZREtzZUNyejBOejhMZnho
            U1ZVSEVoaVJMR0M4c1RyRkJMZEh1NkUKYowqNQObaV6XNjXDfJqd/4UTBw82YYlA
            Ns7ZZFBOSR0JyflFL1A/lcihDOCUPoABxaHHiJlLts4A14BKx8pbrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-13T09:10:59Z"
    mac: ENC[AES256_GCM,data:YJ/xgohkNvROchZkj9nplgKMfyjFJDs3zpDQFWbfmc46QqYwO12ERAXS32IrsmGERuBc0+X77CtHVHrMmQ6lS0aZ6yQlDo7fO6ye0F5VppBnPd/S8ke7mCjehmSNzKDNQkcK1Tg5x5cjmtpVWMtQClFbbknN/IjpEBkdMnD1TC8=,iv:dbILPfYJzCqD2v6m6cGjOrVVXPfn5VijV7T82GhIEfo=,tag:4R33s2IS0ic5a9RLUzo9iA==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
