# secret to test if the encryption/decryption works with fluxcd.
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: home-assistant
stringData:
    HASS_SECRET_LATITUDE: ENC[AES256_GCM,data:/YdAKvdHrA62w5FH06TS0to=,iv:qAr4QStlqRiiwA0vtby5it64Hz3VSykzOXbMcKJkTYQ=,tag:9p7M+I++LWZP4JPln7HCRQ==,type:str]
    HASS_SECRET_LONGITUDE: ENC[AES256_GCM,data:BiA7MqV/15ChK7mBZNdF4SI=,iv:nsvu+sx5MEZzRgtRgpjGzb4oQGpju9VEhVcDaX++JaE=,tag:nRoWVAV12eNO11kXB8n1lA==,type:str]
    HASS_SECRET_ELEVATION: ENC[AES256_GCM,data:duZE,iv:s8Duly/sfS0z9bQDw0Vlt7STKRHPPU2g0K7KeE7JGOk=,tag:QxfR/m4f2K33ke/FbXY7wA==,type:str]
    HASS_RECORDER_DB_URL: ENC[AES256_GCM,data:hFTz2iBwtqybCenLwLckv1c3nKai6KgUMYFzLGBuhAhkfxL6FGp7AJbTqabXfmL2D6Eh41M+b8BXTMpnvitzvGxPsmoBEct6pFI37zXvVDtuGGljsVDY3/0MVnU/qDUGOfEYTsqgluvoeehglTo=,iv:XPkF6uAGOaLN+Hz2c1ZS/wzccSBtRH2dvruXI5OGoes=,tag:kPVXDgA8sW3mITPrenasJg==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:6AHW2RsOJf2o3gQ=,iv:lCmR+ix4kryMRq8Lm9ikI9KPxZ4fgF6VODIm/fjvdAo=,tag:+hf/4XKNaaZvHRRQf7tykw==,type:str]
    TZ: ENC[AES256_GCM,data:UDGtITpTQ1xE1k8=,iv:Sm3ZKfz4G1TV7Ygx4TZtIscVFexT5G8LNGo7U28Ah6E=,tag:z+Wm0qbS73ABOobTBKuMiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MkkwenRSNCtRQUtmQi9m
            RUVQZU1SMGRHYkVnZTZuRXdNcGRhd1pSamtnCjV1VmlaeENjU2hCU0JGM3V5ZGJr
            ZVJFTFRZZ2JwRU9IYWdhRkllWXptZGMKLS0tIFBRNjBZREtzZUNyejBOejhMZnho
            U1ZVSEVoaVJMR0M4c1RyRkJMZEh1NkUKYowqNQObaV6XNjXDfJqd/4UTBw82YYlA
            Ns7ZZFBOSR0JyflFL1A/lcihDOCUPoABxaHHiJlLts4A14BKx8pbrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-13T16:01:30Z"
    mac: ENC[AES256_GCM,data:2m9kROD+IqoDwAfIFrPPVLZhYM+xsThKz8Bke+oTFFQ1iD1vJL930KWtd7YZiC8DXtEVEkWgn+L5GaacC3vDLHN7j8DF0WVMobxz6bi0wvWIBqf6fBv0kNZcgEGNbyoOvMa8PHjjxl4e+BIlypCPRhvYCTD9dwYDhmT1IBBKDiI=,iv:stfWTQjNRC7qxZDOQ+DNcDXg12Vcxzhv56kcU6uUkoM=,tag:7fiYa3nCBSnJL8x2LRtghA==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
