# secret to test if the encryption/decryption works with fluxcd.
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: home-assistant
stringData:
    HASS_SECRET_LATITUDE: ENC[AES256_GCM,data:/YdAKvdHrA62w5FH06TS0to=,iv:qAr4QStlqRiiwA0vtby5it64Hz3VSykzOXbMcKJkTYQ=,tag:9p7M+I++LWZP4JPln7HCRQ==,type:str]
    HASS_SECRET_LONGITUDE: ENC[AES256_GCM,data:BiA7MqV/15ChK7mBZNdF4SI=,iv:nsvu+sx5MEZzRgtRgpjGzb4oQGpju9VEhVcDaX++JaE=,tag:nRoWVAV12eNO11kXB8n1lA==,type:str]
    HASS_SECRET_ELEVATION: ENC[AES256_GCM,data:duZE,iv:s8Duly/sfS0z9bQDw0Vlt7STKRHPPU2g0K7KeE7JGOk=,tag:QxfR/m4f2K33ke/FbXY7wA==,type:str]
    HASS_RECORDER_DB_URL: ENC[AES256_GCM,data:OPQ4JMqgDD5pCSWsmP/4fafa4iXQ1zE+nN1HGqO475k=,iv:L02WmgZgIDVhrEkTAXhTXcsc9PaCm62uqelH+ji+Kh0=,tag:/82IkkWJ9nPyBniCcKq8WA==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:6AHW2RsOJf2o3gQ=,iv:lCmR+ix4kryMRq8Lm9ikI9KPxZ4fgF6VODIm/fjvdAo=,tag:+hf/4XKNaaZvHRRQf7tykw==,type:str]
    TZ: ENC[AES256_GCM,data:UDGtITpTQ1xE1k8=,iv:Sm3ZKfz4G1TV7Ygx4TZtIscVFexT5G8LNGo7U28Ah6E=,tag:z+Wm0qbS73ABOobTBKuMiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MkkwenRSNCtRQUtmQi9m
            RUVQZU1SMGRHYkVnZTZuRXdNcGRhd1pSamtnCjV1VmlaeENjU2hCU0JGM3V5ZGJr
            ZVJFTFRZZ2JwRU9IYWdhRkllWXptZGMKLS0tIFBRNjBZREtzZUNyejBOejhMZnho
            U1ZVSEVoaVJMR0M4c1RyRkJMZEh1NkUKYowqNQObaV6XNjXDfJqd/4UTBw82YYlA
            Ns7ZZFBOSR0JyflFL1A/lcihDOCUPoABxaHHiJlLts4A14BKx8pbrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-13T10:20:01Z"
    mac: ENC[AES256_GCM,data:ydt8ZPfF5h8bfYWNBD5253ssSaLFgdbWotk30wMmUZKhoSGu09vh7OZ/B9bHJxicrvtNdeG7dzgCiE9jY9N0ZqFoi/f+1tknMjss8WB7MsvluGCSArwU6CWSWCIXWpxRp66xu5hM0VDH8FiJUdtj0S+idBQbsN3bHkvFVwM8Y0w=,iv:6hr9JdCq/bC6u9taR18wOlkPtAfMY1o0UYlFJJZkoC8=,tag:G+ZVt0KDV5FH+kzg6TyLKg==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
