# secret to test if the encryption/decryption works with fluxcd.
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:g9G5/o6XpInB7D4=,iv:BYxGOEkt0yIcSo0siL3b1WgCprXVwMjXCiKy2kZ9TJw=,tag:L8KjoUi4zXJ3Fg8tBhPyXg==,type:str]
    EMAIL: ENC[AES256_GCM,data:6NK7v0LcpClxSc1DROkcsyewXfCiZvXyPxI=,iv:Ep5BJCQqGSpvkUbVZrv2IL0iWxalMebd44yA0GmT50E=,tag:u4I3SZgFkarq+pZdcYBYVg==,type:str]
    HOST_TRAEFIK: ENC[AES256_GCM,data:XxwSq7q2oA==,iv:2/wVHl5wMADxmNTEvasN9ZLeArxDrFbKeVrJ7C6Gl4s=,tag:5h0rCEe5qNav8Iw+y8Np9w==,type:str]
    HOST_HOMEPAGE: ENC[AES256_GCM,data:usQ3mwMvthw=,iv:En2aJxWONj4iNFGAxpSE2iY9NRBFZSPloj9SAk3K7qg=,tag:kl9NupqXWWMvnVeEcc9mvA==,type:str]
    HOST_PROMETHEUS: ENC[AES256_GCM,data:n1kkAOOWcow7CA==,iv:s6Es5z8DfxE8k1i7TpTTF+srSvsuMs/EnPl7sIxIlqE=,tag:5P/KdAHJ73adIt8K26FBwA==,type:str]
    HOST_GRAFANA: ENC[AES256_GCM,data:nb+aFn4zsA==,iv:7J+A75xkfzsLGLEUb2iTAAY8mHy2RmmZuXbs3QgcPmE=,tag:BBaGgpVeJY2PHRD7U4MuHw==,type:str]
    HOST_ALERTS: ENC[AES256_GCM,data:pWbqAYTc,iv:Hsng7fnaUT5YwmQtFReoOd5ixEs0+uakHj6evzcXWNs=,tag:e1l4Hv1IhlgL/Exj4QB0/w==,type:str]
    HOST_OCEANO: ENC[AES256_GCM,data:i74+FrcJ,iv:jZj7SDw/WGkFTtDEWd1+vI/Foit+JbHayOeDNwpUXdM=,tag:rCmFy0Md2x9EAdL1vvcvrA==,type:str]
    HOST_LOKI: ENC[AES256_GCM,data:A3QrDw==,iv:qcWjG4tVYspOSEI7zhvYwdM73WHD8GxQg2Q+l38Cm4Y=,tag:kKJIg5sIYrrKJkO/OKw9Ug==,type:str]
    HOST_LONGHORN: ENC[AES256_GCM,data:U+WCkoY6lA==,iv:WLWt92XoWWYlIhg2gCSnL1dXMK7pc5WRzh69GGaUnII=,tag:l5TLfIznJ+AAuKBAe5Siyg==,type:str]
    GRAFANA_USERNAME: ENC[AES256_GCM,data:HQ6XxE4H0Q==,iv:iPNBNJnzkaE+2T+TerTDj+5QeekZNnG+f++grxBQ1DQ=,tag:EJzn3+ilhH+SHzkU8ap9Gw==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:1esVocoFZw==,iv:y5uO3vgBN+Kc/wLcg+0lpXNbRrKv5S2p98xH5g1CJ38=,tag:ZRfcbtOygnn49yxMzfpTEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUHg3dlpPVEdoNmJZaFZm
            bTlBVGI2ZDR1Y09GNkY5ZHZvWER2NXlxWTNjCjR6bEw0Q3QrdnF2Z1ppUHpZZHVF
            RG1mREh0N2JoK1luV1M3L2ZzbnNaTEEKLS0tIDdHRWRKb3RWNFJUMCtDMXMwLzRn
            N1ptZXZaRDlzTkxMdjRjQWdDOXB4b1kK8hsroh7Rwdhgkrgiyjr0U+PH8W5X5+mT
            PhMYpw0WDnIepA/Cta1knGO3ZaKNlLhXHvOevnwXnacNcb90dIBXXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-10T14:59:07Z"
    mac: ENC[AES256_GCM,data:/9v1WIcT3KAqftuUJ3ntL6gtd4m4Xw0m7zURbt+36hposJw8PYXwiC9SHZPBn97a96Ifle0gJWnioN6xibRasiC0iFfCZ441Xx9XwLl9nNjc3DPsQK0Zc6oMILud7wabKkgCyUDyKKyKlbZzZSfnGPTVZy328XYdKxg2JHF0gSw=,iv:+ebz3qXWH0KfZzVOJq0bX1fgLsqD9WWkAh3Yp3X9P8Y=,tag:nA6zHoW5EmtaChhxuJofWQ==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
