# secret to test if the encryption/decryption works with fluxcd.
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:qjW47PjYAAyUTAQ=,iv:HAjhT9XV/yKkGJ0rjbUuqsXrH4lMLsUdTYJMTU2sSDg=,tag:umexHKRB23YDY/+jrF1g7g==,type:str]
    EMAIL: ENC[AES256_GCM,data:ce1lt/7+e25mVrlFdhK6PiUKSEvOPJqwKxQ=,iv:dsm5SVte7PP1i6A7VkLkGZbmMC1Yx9SeiduNiScCwCc=,tag:TQ75lVgBCrpiUm2OiWDOJg==,type:str]
    HOST_TRAEFIK: ENC[AES256_GCM,data:IfkA0d6dKA==,iv:CIZ7FQXdzYNsnL3Xpo7uPjWyt3PWUNgFhtbvW7LIaVc=,tag:B//DmxwflS97tyHKjV7W5A==,type:str]
    HOST_HOMEPAGE: ENC[AES256_GCM,data:G420PZDJwyw=,iv:65ymOWVznZ/qFA3R4DGL0G0w+RGfpO/55MAYdwKDAsA=,tag:UIzwSZblctuyxId4559HAQ==,type:str]
    HOST_PROMETHEUS: ENC[AES256_GCM,data:2GTlLZuTUfCTEw==,iv:sIQo24oc3YwydMAIA/X809A+t7KhOtiJAQszQjIdxYE=,tag:C/MwsA4wiXpPiQhEpLH/SQ==,type:str]
    HOST_GRAFANA: ENC[AES256_GCM,data:1pCpUP7asw==,iv:bz5bstxdEnHFCDI5oyRQWoiOULI9rOki1DgFeRNM+uc=,tag:gRMmOMNMDRZYPsd1IlNC4Q==,type:str]
    HOST_ALERTS: ENC[AES256_GCM,data:6/juIywZ,iv:RJZauwOZH+ZN+rpuSxgxmW3BlxVQ/g5wi6svyvlQwHY=,tag:oFxlwSyNxMeDq2pc8q0aAw==,type:str]
    HOST_OCEANO: ENC[AES256_GCM,data:5atxft90,iv:3fHK0aNdjSvS8piVbXy0FZoSEjtAmI+bjVnMbRVfDCA=,tag:Xh/kQFkRWIt78Fw2fdG/2g==,type:str]
    HOST_LOKI: ENC[AES256_GCM,data:rjBcnA==,iv:p3a+yP+QclpOX1lPjdgr87afG0NVtUec67HGM3EXB4s=,tag:MXwBrzCY4O9eYihCSUu5Ew==,type:str]
    HOST_LONGHORN: ENC[AES256_GCM,data:i7KH1CaVwg==,iv:kVocNTcxp2GzGX6XvXiSU7JwPumkRosSjgYhhGxtiMU=,tag:1NbYmqfzjROqcTJdFDhjrA==,type:str]
    HOST_DB: ENC[AES256_GCM,data:wileLaFEbgqpsDD89jG5Jw==,iv:CGngeyCuVoyRfIz3ZegL+QIKa2LOAu/dJfllQdKFZEg=,tag:cbW54wWJWdXlS2U4hHJtsA==,type:str]
    HOST_HOME_ASSISTANT: ENC[AES256_GCM,data:50s4MX6kN1lG6bwoJA==,iv:5UDW8/rSGdW0snZHBRFrQNzLbSdcqKY7xFOOzVyHsX8=,tag:P6EWZyVK89jtAbL+gLc77A==,type:str]
    HOST_GOTIFY: ENC[AES256_GCM,data:2+y2PlDD,iv:GIbBvr4yCAHiMFAeMAwGjnDJH918rIVXHJWbSKtx1NM=,tag:djhzVpZ6bTtu0SR9W5CNYQ==,type:str]
    GRAFANA_USERNAME: ENC[AES256_GCM,data:54geit0kaw==,iv:AvgqnOrQN/KOmX27Bz7J1dMjNLH4FR7RqJ+mtt0Diqc=,tag:iGZu2noDYNxaRUIrVfuT8g==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:VG49Lc+v1Q==,iv:6+JVa3Vq2l+I6uCzuGBgnN5GD6MO6L5nmZLajVO07R8=,tag:E34QpqDkWAw5FDUztZd8bg==,type:str]
    GOTIFY_USERNAME: ENC[AES256_GCM,data:tEgme320Ig==,iv:MSXcaTn77FAzqyJhbcRDd3brnv3jpWsMbBK5fB7nDC8=,tag:bSzeo/eT9ZOGQMhCWseY5A==,type:str]
    GOTIFY_PASSWORD: ENC[AES256_GCM,data:I0YVGxa+6DsSNMo=,iv:PeIRfQ4iMiUtTk5eZCObccRnhc5NkBBvD+2MgTSSl6Q=,tag:qNo3NCOymAiKsfsdxsMNHQ==,type:str]
    GOTIFY_DB_CONNECTION: ENC[AES256_GCM,data:IFg7wThpPHbbUIbrYwls8EhPLX17JcFmuB7fou15HsSGuc35TeuP6nORZkxFyMveWvll6Uan263OiylPLEI/KBO1tRblPOzSUsGgZr7hDP4+cWF6mx1zJNI=,iv:h4646XPmsiqKW8srHVtps/HcE7FiXXe8UxuSHEVW3Fo=,tag:tLMO0zd03PSAiPevW5OqTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MkkwenRSNCtRQUtmQi9m
            RUVQZU1SMGRHYkVnZTZuRXdNcGRhd1pSamtnCjV1VmlaeENjU2hCU0JGM3V5ZGJr
            ZVJFTFRZZ2JwRU9IYWdhRkllWXptZGMKLS0tIFBRNjBZREtzZUNyejBOejhMZnho
            U1ZVSEVoaVJMR0M4c1RyRkJMZEh1NkUKYowqNQObaV6XNjXDfJqd/4UTBw82YYlA
            Ns7ZZFBOSR0JyflFL1A/lcihDOCUPoABxaHHiJlLts4A14BKx8pbrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-18T21:49:05Z"
    mac: ENC[AES256_GCM,data:Ny5JSZ3UC2Ck6BEWKn6XFWRA9lgv1t8PDCjApP0s0l1Q326/0CCFPQzKT+90lKD1LbLws/g8PKbCGUW+sMeRW1bPAdu4i/jg3VkXle/65mBi66kqNehKoAdDaK0N3tn0cCYSAhjRZTTra1HSSVR/B4ie+2/vhDPamUhd8lX/DZw=,iv:zEfjlt4a5qqkMhbwGDIqhSpb2FidJpylxDQ5QdTWlJk=,tag:TPm92MIw27LasMb3MFqlcw==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
