# secret to test if the encryption/decryption works with fluxcd.
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:lEPxf9c2ppXdb7g=,iv:pPemECeDU0O110x95s6TGUXtoX6YHGMjCXhZNHZ09Dk=,tag:bqk+JvlKaFvQGMWcIBojxw==,type:str]
    EMAIL: ENC[AES256_GCM,data:+XoC5gmlGd0nWCpcZZ1zo8l+QFSEanfLKyc=,iv:3IUPy/13Ixs8Wg8I3jheGsNr2gtR0afD7rW6JZWF7ng=,tag:COfkKHS8u2RWjMt0t24ogw==,type:str]
    HOST_TRAEFIK: ENC[AES256_GCM,data:epDuhovMrQ==,iv:kJBQkA2r2X4TF2LOn0hQPd8ZlxYX4OwhUqGoFvxNJ/8=,tag:vQIID8OUEHTQs9ibm+UbUw==,type:str]
    HOST_HOMEPAGE: ENC[AES256_GCM,data:Mvky52jEgJ0=,iv:4pNfWjF+eEgXHThb8kItuBzIw5Lw84ODTZXZncpQ/oE=,tag:hT/CfXGxPrXXJKyVzCGbPw==,type:str]
    HOST_PROMETHEUS: ENC[AES256_GCM,data:GT7mHeE/Es6YIw==,iv:sL5omgKr+g/7TP1fu2j5jho4sFFqwgv9G+nVj2RxnYs=,tag:9BaS9Db2EH4so5VXFMyqFA==,type:str]
    HOST_GRAFANA: ENC[AES256_GCM,data:z7xCFuUcNg==,iv:SNY+gEHJ580fF3jp1wNEg6ACcrYyKcCU1MkOJBlvgVs=,tag:EDxwu+xY6ty9laUbZJeV+w==,type:str]
    HOST_ALERTS: ENC[AES256_GCM,data:nxB5/x+p,iv:9d+gjWlfv/TGybLpj0T9Pscjru51oKPmhUjiLbeXVxU=,tag:2JiCFkTVGOLDTDGDv2Ddgg==,type:str]
    HOST_OCEANO: ENC[AES256_GCM,data:MwzeVv9k,iv:ftnvxFCE2da2s4fsiaqN5A563k52W1KMr3IJ2TuiVV4=,tag:t0CA3LDXzbnJGWPHHU5fHg==,type:str]
    HOST_LOKI: ENC[AES256_GCM,data:aCeTgw==,iv:sW9Yo6rFPDxQkLNa1/WU+k1HapY1RK3UNDKjfANeR7g=,tag:hR5lL5TCDD88AcDui5/SZw==,type:str]
    HOST_LONGHORN: ENC[AES256_GCM,data:I1c7wltoLQ==,iv:mOJ2Q5n4Rp49it419ksO4CE774r4JN8PHrAp4a0dNSk=,tag:icy8DH0crEZCqRosWCOw0g==,type:str]
    HOST_DB: ENC[AES256_GCM,data:QQrR7bffzk0f,iv:JFsSrX50hqSPcYaL02n8uekpfWqb5sy8yelV55eMNVc=,tag:WNIY5vRcEvDJ6vsY1EhZ8Q==,type:str]
    GRAFANA_USERNAME: ENC[AES256_GCM,data:NSXwrb/Zfg==,iv:irkr51YpZEp3SqQblRv63JNjsDygD/06PS+liV3ofx8=,tag:pNg8IbKIhtTCHBao2W1Y3w==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:EcQQvgstqQ==,iv:DAsChckMQ8f2XkFYgKqLMlxdW4GMFlXD8+g0O2ZuiSM=,tag:+VU5N0rfRX4Qc/9QMFwcdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSM0NDd0tiVVdneGVIUWZj
            UjM1OElWNHAvNEhGNWRGUFlLK1JRNmhUZFVZClMvUDltZEpFMSt1ekJMNXlqbC8w
            Y3hTeVhJWnJWRnM4WFlHSkRZYlUxNDQKLS0tIG1wRW1HMWZHQjZVb3dNZUxDQXo4
            NjlPZjFLSFpCQ1BlTk1Bd0dYVjJGZ1EKGBOfQjPCEY1PCncOzvCjHA1cV+/EcDsK
            QIvdxzh4kmokau6nG8v9rlk/O1gJZ+JpceLcaPAfR/QU5U2e7WRm/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T08:03:56Z"
    mac: ENC[AES256_GCM,data:2iEC1Cy/b2Acn8Q+bkYkZu8NSgBNJ3FkzIONbFKQwixo1ZXWvIRNQaSdjh//oWG1uovYztuI/7Wsolv+dfnxdUXVWw5kNNoTEbCXj/xPbQuKvy78fkQ8M14sODaCCJRLgdelnUc+EeFxC38xX5NgbN2QJVtBowkJuxqynqAMkYE=,iv:5IKoDRWYmXyUvl38eoDO+oRFmG8W2N7HjoogvWyrMI4=,tag:jI/i2GJsY1G75TihJ3k8+Q==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
