# secret to test if the encryption/decryption works with fluxcd.
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:T7tqficoes04LMc=,iv:MmlMIvvis6wEHB6KQYF0siaG4SYXodtpmDmpatjBHlc=,tag:/E/QzN/AI/KMA5aes3hSSA==,type:str]
    EMAIL: ENC[AES256_GCM,data:yymOLvBdE53Hdq7TKt/QWQCUkyD2J7CGl1k=,iv:yD8Tw/muRV7xPggofI6iuZ0FmgUc/UmYf5Sx+q4rYRw=,tag:7LAqSiLbYuuPkfO8oNh6iw==,type:str]
    HOST_TRAEFIK: ENC[AES256_GCM,data:rTQfveTTWg==,iv:VbpBQHWutyxZt0yknrvOvwSLNnxmc3W1aJgKbUixFyk=,tag:eqqZr0+5Qr/nxOfY9wfYNQ==,type:str]
    HOST_HOMEPAGE: ENC[AES256_GCM,data:pr5OWYRp6B4=,iv:dsvK/nsF7mK2j+yrhhRc2oK8QIOX6WKPJ3FebU3bk5Y=,tag:tsU+u85Tvq+h/ywxVKxSQw==,type:str]
    HOST_PROMETHEUS: ENC[AES256_GCM,data:8UOcpa6ppj2TkRZIt4jjvgiOdmg=,iv:anx3Rui8cpNnNbQD5BpDJuZqbm9Eg0ySJSk7VbJiBGk=,tag:ZCW3lI9Llf65ZSeHCZuOaQ==,type:str]
    HOST_GRAFANA: ENC[AES256_GCM,data:oQNwexF9tg==,iv:VBdCaCe68WgLwyqPHxmE+yK3CFtg7OzJ/MCvt/+ibqo=,tag:b1HAyPN/D9KaroPtcYW+uA==,type:str]
    HOST_ALERTS: ENC[AES256_GCM,data:0mOqmxwb,iv:44Uw/7tLjrnsIViug7JqHK+GZlWKd90ZWFsziwNbdAM=,tag:6v1Jr23ZQayeSttff4YG/Q==,type:str]
    GRAFANA_USERNAME: ENC[AES256_GCM,data:mCBolsGiKA==,iv:e4ngcfuq2ZFlS4gYCUvgeUXguS4VARTV5MKzEhc5Jb4=,tag:VLDG3ceUAOKfw2F2sD9mCA==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:wmlZFyFsiQ==,iv:h+edwdlFxZBwlQjbSkOtIRbuk0lPQDcOPaLsmkjniDw=,tag:sOHXftcAzsjFiu//m6ORhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMW8xRWRDQzlXRGdOSis4
            My8xVjI0bEtCMzEwRlFXcU5TUnY5bjlZQ3pJCmR0cGlQQUkvVHZRSVhWck1nS3Zh
            TWhlaDhvRitNTUtZU0FHaldPQ0VHYjQKLS0tIDBKblcwelRuV3l6dnVzWjIyUFZy
            SUI5OWhpOHZyd2lQVXZ1c3M1RFZRQ0kKwfv0kIuRbbs59awKVM85M8xGO563RQzF
            w4PLP63lzlhrxNWGbpJj92//+zB445MiouMrh2Faim3ype0FqJ+GXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-07T14:39:06Z"
    mac: ENC[AES256_GCM,data:azEQRoEHRDnO9I8XTHGhug8zxMqkQL0/n689PwUV9okHUvXgWhkBuSGocHskw/JomaVgqxwsjidiWTIF5i0p+png3/ktJDT5BnF4LAHyLSer1kIBWFku4zYCOkWeLvuejRdqjarO5HWIuBpzPMsgBVhZoHMtbrSEaawPb8ngtGw=,iv:7SLmdtVaa8Y4uKuQRAyQMD1PeSUJMTJoj9VpeKzu4VA=,tag:n0NprnPGgwcS+v91jfjBjw==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
