apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-settings
    namespace: flux-system
data:
    TIMEZONE: ENC[AES256_GCM,data:GBT/CE9dj4GW92g=,iv:20vsKFMCOLUGFZLDw0oLmfhf+1ekTaiL7dlfSL9VUOY=,tag:qmGJeI7A+MbIlzGE/E6lvA==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:kpWQUUS04ps=,iv:j2DHwmyRBRA8E595y7zI3J0plnLZja/u+SddZ4Z7sFw=,tag:2wxcL4Zo970C5beH1zOYNw==,type:str]
    RUNASUSER: ENC[AES256_GCM,data:qj1/VQ==,iv:UzJkT7xdedE7womAKABqzrPustiVGP1V8+GdxeFzzqM=,tag:SmOItwYNVdCSPgr/ZuFlbw==,type:str]
    RUNASGROUP: ENC[AES256_GCM,data:bWAQ7w==,iv:3fZTqNkBQCbFYWWWVXtefO2nPDwGKMEA/+oszqElu0o=,tag:VnXxpShvmK3Q0Qi/zprdNQ==,type:str]
    TAILSCALE_OPERATOR_TAG: ENC[AES256_GCM,data:GtHMiG5matSfrC5+kqZzoDD1xYdC4pQjKGbCTZ2jfdPowJDBSSwy6dNIBTJBhQ==,iv:W7kvBKppUbiG+fKPL0I585Mh8nideSSxkAFtNQNTEB0=,tag:RAf4e+XRQP7dBnr72x4MlA==,type:str]
sops:
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WnZzeG9pYUFGY3ZNZEc3
            dVJoYUxKTGdUM1NYTFdDZmtvQklYd2ZsakdRCjI4Yk5uM090MjFJWG9IZmVyODRN
            c2N3aFZoTWRNNG0vYTk3UXRrMHhOMU0KLS0tIHYwMGc1U1p0aGc4TzQwRW5DaTVy
            U2U4UVgzNUhLdTFuRU9CbFBPUU44cUkK57Aln6Qa5af/ULN9DiLDLjMbBtTe5BWo
            T0Po6rQ7St390Bk4p6J1BxDE9WeGvN8C+s/I9SLmsk9XZXtAAgSpKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T18:46:57Z"
    mac: ENC[AES256_GCM,data:ia05zM4Zk0VH4Vt1pLAfNXo1IKfoX7zdbb5HYQBK226t2fiJ3fCw+iBjBTWCldlj7vwcepB38S1GK6pbFGi8u4PkllV+VA7ZYjh2JikrtswYr3TbUX/Rltc8T/fmYzBLPVVB1n4mSsegZVpZxOQUUeQt6Pm2d0Uso9A5ak4rLyI=,iv:ky2U1V3xVcs8rFg/l7vTZCG3WQ9KNaZSSZTHo7pZVwI=,tag:R5ILXdiOs0l9a2STWTiAqA==,type:str]
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.10.2
