# secret to test if the encryption/decryption works with fluxcd.
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:O1OzpYH8NXDga9Q=,iv:nyzs366NNzc2P6Lk23/0EyWHsvAcR15OeBPWUeZu/88=,tag:k/Rl4P/HIF/kd9HgiaaqDg==,type:str]
    EMAIL: ENC[AES256_GCM,data:DUUlc5/4oxr4z7YQ8PIWeLcM/O73VWn7a4s=,iv:IC+dH+eD0tBUFGINilucQT1vhM8uBoy+8mNshzdmheg=,tag:3zB0XZYiz3Uxapzq7WiamA==,type:str]
    HOST_TRAEFIK: ENC[AES256_GCM,data:WFIIHqqvAw==,iv:19hAUDo70DHz2cHiiZ1JciMmDGYt6vdv3sxFJk+R+uc=,tag:NBUP3GJY+Yv1xukXo82zWg==,type:str]
    HOST_HOMEPAGE: ENC[AES256_GCM,data:LRkjsedum14=,iv:34/n+s5D4IACIhoQ+1dNcqovcdZSrQtzJoL/oLhc3a0=,tag:ieEuR7YQwV3tJYSxzf0TjQ==,type:str]
    HOST_PROMETHEUS: ENC[AES256_GCM,data:zYseqJ/f2D6Eeg==,iv:biFUPVUfAJwefAo4kiN8vzzkGIwXG9bU+FfvXz5QV5U=,tag:Zcjyev689JRTe6IhU+Y7fQ==,type:str]
    HOST_GRAFANA: ENC[AES256_GCM,data:dCglAeIOxQ==,iv:bI8B30kDB4t7GCYJLwFjDmIRSUNUD+zVRjZGz14mqo0=,tag:jYuORQHVH3L7njVYSIFGuw==,type:str]
    HOST_ALERTS: ENC[AES256_GCM,data:JmZYCy2Z,iv:L0SuDUzYptjfdGHe369dlvTWKGg4aHrNHkGgRbfUqEg=,tag:l/jFJwJOTkVdli64WDOUPQ==,type:str]
    HOST_OCEANO: ENC[AES256_GCM,data:dwNAScwm,iv:+Ny8W62kOWUL7PWMhTCXAYeePgEmUxfOsAbPqIwu3N4=,tag:N33HOqQcdBvh5tsa8HmTqA==,type:str]
    GRAFANA_USERNAME: ENC[AES256_GCM,data:AE5wfTL50A==,iv:kB1sAwKIu3uYqjBUVN/WFNHJq2fcXuwmN5gkTSW2VWk=,tag:CwmGOpF42RQSukiNFbfL8A==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:JNgjalanXg==,iv:HM1oeKG+0J0bH/ny1T9NvgVKbztx0oeCWWK3dTMt8GM=,tag:uXQeu0nmfzEBWIag16ELmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdEFvR0xXV0U4UmpwU0NX
            Z211bWlsOWl6YWFlQi81VXFkM2lWMzduaUVzCkxFWjlFTEM4RVN0Vzc0QWtra0Zl
            NCt5cmtpS0gyeFNFLy93dHN1K0ppL0UKLS0tIC9zcFcxVkFlQVdNdU5PS3NZcGtT
            dTNsTWM3WkdTTStVYnJSUTBWbFdJVmMKtaGP/NLypgGXfSfEoWNijsDTpGDuqVE4
            KoiYzwPKPbAsQC4gosYJRl94lAhJCuVHwxman9UhZuQLeRxEksHZhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T07:55:25Z"
    mac: ENC[AES256_GCM,data:Hq0Lurfhm0AkHr/FO8BUjjhkRNo6Ed10Fl300dyx/compiGUOU4qnCpRexUwuFEliP6PqYqOPe0ZN9KZgi8BILWrD8MPC+fCDONYV+BGyqvoV3XJ9/NDg6AdYhvyCBYAzC9SzhwX6ScZkRdsnTG+FWauarGNEOt/S0BGYSif9Hg=,iv:uV6SoyRD5sOBTzRxkgO3Di6i2HdBvpOAT4ZCQl6U7z4=,tag:h3GQco6OJdk6I2JoKQ1M9Q==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
