# secret to test if the encryption/decryption works with fluxcd.
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:sz9++hAwyYlZ7j0=,iv:qQE/ox3ta1SOMsqAWSNw/cL7qd8M0plxyVLr0opqH1c=,tag:7fWc5V0EXKnjiEEtDlR6Jg==,type:str]
    EMAIL: ENC[AES256_GCM,data:ot+A+hBygZOIgeJ/kREngau6Q9zyQ+SI5ok=,iv:/5RbWNgiKIdTnLRRWvCARYp62CiYMF/9N+97fZNg8Lo=,tag:mbFpP3+jAwCtW+KFic3DQw==,type:str]
    HOST_TRAEFIK: ENC[AES256_GCM,data:a37hzqVJOA==,iv:sn+khntxqLp7R4Ox376m5DtVG53yMXhcLg2ogXNMsXY=,tag:6YKM+eVKUUDtXChMTXaKXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSHlpbDNCZTFDNm13L1Fo
            WGVyTWR5Qi9oT1JCODU3UWpsTGtaYVl0a1FvCkI3OXczWWNBRXY3SzdTdi9hVXd6
            YTFTbXFZVnIvbHBnSUxjNXlXcmpraTQKLS0tIFZpQXFNS3VmZ29nUHo4bnd6Mmh3
            VTVCOUk5dm9oT05nVjZybkZSN0Vsb1EKzI6Hh1GncVrOTx0sYDjxgX187LG5UIsg
            x7S5fZ6VIH8ye6OxLQG+Rvs2vLhqDzC0Oo8Axp1BVDmIp+HfkUsVEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-05T13:46:16Z"
    mac: ENC[AES256_GCM,data:/iTNl7Wrl+eqrgfGoieSIjhbgZz797ULIIPHZej5lPSGWA+hXj3oLmipxXXu3rWuzHG1XO6A8wvOmS/0NiCotXEpX4ni4dLYB6/SSUdifTkf4Az+PZpyJW65KYBkelb7PTz/0UIG/6sm6CSaSuwScE/CYJXPl0l5m+Lr5I/hHR0=,iv:z7EbzQ/+/T6NOnJJKAzP1COM64YlqeBhKQ5RK6zqM00=,tag:vroxrnCZ0OG0gN4QU3UdCg==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
