# secret to test if the encryption/decryption works with fluxcd.
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:PcydRN1IBmGNlA4=,iv:v9aQTgwRYpLAyLJMXLBR9eh1U3BG6NlaIYq2k/qopyw=,tag:5BNr+6eILNkIRHVkDeaJvQ==,type:str]
    EMAIL: ENC[AES256_GCM,data:/IE9FWg1bmzFWvwucAazrLHhNzL/u/hXTPI=,iv:GnCJLuaIjxrfJjtgQ0ILzsfZ+unJsu43+WynBMUNm8g=,tag:X5EeJ3MAYIGQKsZotz+mhw==,type:str]
    HOST_TRAEFIK: ENC[AES256_GCM,data:Lr+gSrylCg==,iv:wCRLNACW8LE8M9PU2d1g9VCCNIVJ33oS5rkpyREz5nk=,tag:Pb3s6jFoC2N+UZAHZmHsJw==,type:str]
    HOST_HOMEPAGE: ENC[AES256_GCM,data:bMKvWksvjN0=,iv:7v352jK7VHDXwkImDwgOD8BcF97Q1atVElFyjjDkWvE=,tag:/3P3couzBWv/72i5xIo3JQ==,type:str]
    HOST_PROMETHEUS: ENC[AES256_GCM,data:uLIAU8qWzfwYFQ==,iv:ifTpfIDNyJH8QS0bgzcl+gAdZG7BnnmA2S4W/HS2PxI=,tag:Kd/89I+dJqSdSxNIep5w8w==,type:str]
    HOST_GRAFANA: ENC[AES256_GCM,data:DUWfNA9O8w==,iv:MrWvF2rIvzxOdQnmC5PouXMV8wko42jW01H2dPV+Qww=,tag:teFoON5h1oGq/Lq89VNztw==,type:str]
    HOST_ALERTS: ENC[AES256_GCM,data:SiPUd8Mb,iv:uerfgrW2MKaAKgruPD4P4Ut/Dsx+ny66gwUQuYmH/LE=,tag:E7Wm9mSWsE1uHTtHaBHMZA==,type:str]
    HOST_OCEANO: ENC[AES256_GCM,data:GdoQK34Q,iv:Tc5zh0u0QnzJz2YsZ1OfezpxUdnO93cUFGK6GS8si1A=,tag:wIqyxE47XyFcKuLSe8j8LA==,type:str]
    HOST_LOKI: ENC[AES256_GCM,data:sbg2fw==,iv:S1VpTCJtko5MQr+T00F9EqRDw9Y0Wwuhc8tT5SMegqw=,tag:P98VpKPIksPk/i0YADSfBw==,type:str]
    GRAFANA_USERNAME: ENC[AES256_GCM,data:TRcVe+dCSQ==,iv:eoJRbmH1MdgYpU9JDPLLmxvn2xTQijVsfQE7G4CgenE=,tag:rabq4yn6uwJS1+N558qqLw==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:1MKSq4Ot+w==,iv:fKvTTyBYbpWS0D5gIdHNpekXvG3/oF5dtUhx6zWhWiY=,tag:pUi1Ds3lgFQGGj6VaRUNVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveGRRZ3k0WlE3aHBVQjEx
            YVZZUkNhSUFGWmc2RUhBZlRNR1JsNy9zZUU0CjRYcWJla1F1dDczZVNqT2JOOXQ3
            QkRnKzFzbWt0a05DNmZqUnNVS2VRYWcKLS0tICtLc2IwQU1sdGNhSTJHK2RrTEI2
            MmFKUG1zTHNpcnBkak9UT3FFdmhReGcKoqqOyq9Jj8smM3Ta/ZAiiDFLJzK1BzIj
            cQGRZplakCJfEA8cg+BG4hZoCy0CQLuHggykiEQq97gkKv5fR0/d3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T12:38:20Z"
    mac: ENC[AES256_GCM,data:zFG86yusiwMOzsEgwbtPHN/2RnlZYjE11hwauxihmE6Vi3EfKPVk2VYC0QhAfSlwrUK+pnzlDVbyGcpasb0P74NCVl2Ri2iXpYYEPQtJYOZpPEKOTL/0lh+lzlCEZjMC7Ik3+Z6VFm3BBDd2L4RkmmfAdgwQTb+/Txt0JhC4D+U=,iv:LwOkx1TUjjqn0Epy321RppYT7jAl1R5sg1jhSo2ueUY=,tag:59jfCJS38sozOynzgW9Cgg==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
