# secret to test if the encryption/decryption works with fluxcd.
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:qjW47PjYAAyUTAQ=,iv:HAjhT9XV/yKkGJ0rjbUuqsXrH4lMLsUdTYJMTU2sSDg=,tag:umexHKRB23YDY/+jrF1g7g==,type:str]
    EMAIL: ENC[AES256_GCM,data:ce1lt/7+e25mVrlFdhK6PiUKSEvOPJqwKxQ=,iv:dsm5SVte7PP1i6A7VkLkGZbmMC1Yx9SeiduNiScCwCc=,tag:TQ75lVgBCrpiUm2OiWDOJg==,type:str]
    HOST_TRAEFIK: ENC[AES256_GCM,data:IfkA0d6dKA==,iv:CIZ7FQXdzYNsnL3Xpo7uPjWyt3PWUNgFhtbvW7LIaVc=,tag:B//DmxwflS97tyHKjV7W5A==,type:str]
    HOST_HOMEPAGE: ENC[AES256_GCM,data:G420PZDJwyw=,iv:65ymOWVznZ/qFA3R4DGL0G0w+RGfpO/55MAYdwKDAsA=,tag:UIzwSZblctuyxId4559HAQ==,type:str]
    HOST_PROMETHEUS: ENC[AES256_GCM,data:2GTlLZuTUfCTEw==,iv:sIQo24oc3YwydMAIA/X809A+t7KhOtiJAQszQjIdxYE=,tag:C/MwsA4wiXpPiQhEpLH/SQ==,type:str]
    HOST_GRAFANA: ENC[AES256_GCM,data:1pCpUP7asw==,iv:bz5bstxdEnHFCDI5oyRQWoiOULI9rOki1DgFeRNM+uc=,tag:gRMmOMNMDRZYPsd1IlNC4Q==,type:str]
    HOST_ALERTS: ENC[AES256_GCM,data:6/juIywZ,iv:RJZauwOZH+ZN+rpuSxgxmW3BlxVQ/g5wi6svyvlQwHY=,tag:oFxlwSyNxMeDq2pc8q0aAw==,type:str]
    HOST_OCEANO: ENC[AES256_GCM,data:5atxft90,iv:3fHK0aNdjSvS8piVbXy0FZoSEjtAmI+bjVnMbRVfDCA=,tag:Xh/kQFkRWIt78Fw2fdG/2g==,type:str]
    HOST_LOKI: ENC[AES256_GCM,data:rjBcnA==,iv:p3a+yP+QclpOX1lPjdgr87afG0NVtUec67HGM3EXB4s=,tag:MXwBrzCY4O9eYihCSUu5Ew==,type:str]
    HOST_LONGHORN: ENC[AES256_GCM,data:i7KH1CaVwg==,iv:kVocNTcxp2GzGX6XvXiSU7JwPumkRosSjgYhhGxtiMU=,tag:1NbYmqfzjROqcTJdFDhjrA==,type:str]
    HOST_DB: ENC[AES256_GCM,data:wileLaFEbgqpsDD89jG5Jw==,iv:CGngeyCuVoyRfIz3ZegL+QIKa2LOAu/dJfllQdKFZEg=,tag:cbW54wWJWdXlS2U4hHJtsA==,type:str]
    HOST_HOME_ASSISTANT: ENC[AES256_GCM,data:50s4MX6kN1lG6bwoJA==,iv:5UDW8/rSGdW0snZHBRFrQNzLbSdcqKY7xFOOzVyHsX8=,tag:P6EWZyVK89jtAbL+gLc77A==,type:str]
    HOST_GOTIFY: ENC[AES256_GCM,data:2+y2PlDD,iv:GIbBvr4yCAHiMFAeMAwGjnDJH918rIVXHJWbSKtx1NM=,tag:djhzVpZ6bTtu0SR9W5CNYQ==,type:str]
    HOST_UPTIME_KUMA: ENC[AES256_GCM,data:xzIgEDFjFFLEdw==,iv:LxdHH2MGofk+/FQaYs1WaO+tkxDLTyRLcNN9/KBtHVE=,tag:M8d36GimBT3ihnDXr85YpQ==,type:str]
    GRAFANA_USERNAME: ENC[AES256_GCM,data:be5bX5TtZ1UDjWLt,iv:UezyTec99cUb2+z6ETEQk2Pwq7Dl33jvYoV89ouMzJs=,tag:DjeYZLETFmEkGvU9nQAqHw==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:VG49Lc+v1Q==,iv:6+JVa3Vq2l+I6uCzuGBgnN5GD6MO6L5nmZLajVO07R8=,tag:E34QpqDkWAw5FDUztZd8bg==,type:str]
    GOTIFY_USERNAME: ENC[AES256_GCM,data:tEgme320Ig==,iv:MSXcaTn77FAzqyJhbcRDd3brnv3jpWsMbBK5fB7nDC8=,tag:bSzeo/eT9ZOGQMhCWseY5A==,type:str]
    GOTIFY_PASSWORD: ENC[AES256_GCM,data:I0YVGxa+6DsSNMo=,iv:PeIRfQ4iMiUtTk5eZCObccRnhc5NkBBvD+2MgTSSl6Q=,tag:qNo3NCOymAiKsfsdxsMNHQ==,type:str]
    GOTIFY_URL: ENC[AES256_GCM,data:JCVgp1R27jjAJvgC4ZbEYXf6PQe/Bsp3uIK0ggopOgOcj5SjSvWnPQ==,iv:q+6VVPVxh46TaX+gJMtJAulJnr4OYxPbCyeCgAnDLlA=,tag:ANmTS8fYZoMs0NeLN0tHxQ==,type:str]
    GOTIFY_DB_CONNECTION: ENC[AES256_GCM,data:ShIlf6e4EmRhpyV8Cr6mv3QgQg7DKSRrB95Kqr9INTftPAVYSNnKaHu4BZkDk7tunkonxoB0jwxdiumiddQ+iYLRd+9GGSAMAOjdc8oJoC/QUetbsoFw4x/4jByw1FQmTN7jRbB2IMj/Tkk=,iv:uttGp0OuFwaQlFfJbrwnhFlgvUuG6pttnnWvaiP0Q5I=,tag:srsvMlPmqFwXu6QzdCcyoQ==,type:str]
    HOST_IGOTIFY: ENC[AES256_GCM,data:f0/IXzCzLw==,iv:WzPZ/3n2SHZU3zGDZQUJ0h5sHLL0Yvy7GlsoYi6YUig=,tag:BR92arVMR+/uSyN7LuzMLA==,type:str]
    HOST_PFSENSE: ENC[AES256_GCM,data:1TWvyNAjt2g=,iv:fARVzloPZIm4ioB7fwbYcT2KOTogFEZRwUZbs8dEMuE=,tag:FTUjgJz0NZ96mZSWkKOv7Q==,type:str]
    GOTIFY_APP_SMTP: ENC[AES256_GCM,data:W9ZazHZBbuHHsZogrWn3,iv:PZSU9zV+ReOGuIaqJOi1OfJxpfzyMx4mM9BtyymolGQ=,tag:iFkonKQ1Y704PtDrokL+vA==,type:str]
    GOTIFY_SMTP_SERVICE: ENC[AES256_GCM,data:vQ821euxthycz70=,iv:FejWLwLHiAOFvRZMnrdA7BSQS87C4obHLp7n1txqGUE=,tag:bxdBdu/6XxCG7ekdbfZS4A==,type:str]
    HOST_SMTP_GOTIFY: ENC[AES256_GCM,data:ugGONyTg0ohRwjc=,iv:vDoOCE0CrKUc47DAuZFnmzGRYI6uR4T+Xhz39BsmfWQ=,tag:NGpYsQB4vy8PaywL4bT+YQ==,type:str]
    GRAFANA_GIHUB_CLIENTID: ENC[AES256_GCM,data:OL+6SUBHpnKISpEqqLqlJyjUiSs=,iv:yD7RTDoU+KAhrkSahuzH9Z5btl1Z7qN4qDuwULJcwZE=,tag:DzDdz6ighwNx/BcodytJgQ==,type:str]
    GRAFANA_GITHUB_CLIENTSECRET: ENC[AES256_GCM,data:ByA9Wsvh2Fh7sdCs/ZfCVTAiivtLm1eihUKlOm5Ws/c9bGTjKasWLw==,iv:4JGtBbE+gps0SNLfd2CWSwPmT/Beh3B3SOdCwa1p7p0=,tag:8I0dUnGUhvRFz+LgdhBLEw==,type:str]
    HOME_ASSISTANT_DB_CONNECTION: ENC[AES256_GCM,data:pknSPhK8BDISkT5KDfjxu/byWYw7x0+B2WinKH0IgWgjzXnstjsK4JZviA3txJL4t9sasjy8WVMjnF2GGFQGT0idgKU2HwIApuddDeM//lcJP7ThUYrKcBloMJFSrUYGZJnKccR2dXXXGRNdYezhNyuyWQv9dMK0bkPsLEJ6OeA=,iv:aoMXWzEJCJbI0+aM9JGakVoXLiPQZNUr+wrsnyviQRo=,tag:gm79ZGAVMHQb7Ff3IGUorA==,type:str]
    UPTIMEKUMA_USERNAME: ENC[AES256_GCM,data:iRnHfI343g==,iv:yOyNlKP/tM6+4eP5mwTRbEs2u6GcGJ8qizw8Ed4ADU8=,tag:5AOVM5BCSBa2+/OkMLSCPQ==,type:str]
    UPTIMEKUMA_PASSWORD: ENC[AES256_GCM,data:xcGmBMHr8Bg2SA==,iv:kKP3h2jfLvaDsRKS/A7XWCsPxJAHaTguInPywEfOltk=,tag:9K1XTfH4EifQ4YlN9N38YQ==,type:str]
    UPTIMEKUMA_SERVICE: ENC[AES256_GCM,data:sC9276weBzFHcPA=,iv:dD53VYcENwHvNqzycqHnxs/Tg5LseQOHUIgTBWCgEU8=,tag:uIZU2zf9X7khmBXooxiJuA==,type:str]
    HEADLAMP_GITHUB_CLIENTID: ENC[AES256_GCM,data:/jhTO6kf+7WkjjVYMLvNY3UK93w=,iv:AVpVXauFafsjBufArtXohnvbiH4W0s1Rwf7tCM6tv1A=,tag:5LAWsJ59YFf0J+zNmIzkcA==,type:str]
    HEADLAMP_GITHUB_CLIENTSECRET: ENC[AES256_GCM,data:TUfSsaXhAGbN8otBB5NJwYonfIj0JhHQIAoHoqxO2OnvmFlMBHF5Yg==,iv:HhKZL57UaT45TxASuGkTisGcO/S5FDz6NdCt60pLqo8=,tag:oUwcD5sySz+MuyXABHrlPA==,type:str]
    HOST_HEADLAMP: ENC[AES256_GCM,data:QWEpUo+cxzg=,iv:UnNmiQX3oHLLn6bQK8RprJE3jfPkswcSSXI6T01QafM=,tag:tUJg9LdTFbvfGPDeGd+g+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MkkwenRSNCtRQUtmQi9m
            RUVQZU1SMGRHYkVnZTZuRXdNcGRhd1pSamtnCjV1VmlaeENjU2hCU0JGM3V5ZGJr
            ZVJFTFRZZ2JwRU9IYWdhRkllWXptZGMKLS0tIFBRNjBZREtzZUNyejBOejhMZnho
            U1ZVSEVoaVJMR0M4c1RyRkJMZEh1NkUKYowqNQObaV6XNjXDfJqd/4UTBw82YYlA
            Ns7ZZFBOSR0JyflFL1A/lcihDOCUPoABxaHHiJlLts4A14BKx8pbrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T16:06:13Z"
    mac: ENC[AES256_GCM,data:TafQW6JFnNUPO5JVJt0ZInZduYzOpUBBXLDiYiIXpw7Ua4B4qR3Pe+1ZSshc9PJyKfCkk241nEoYupVKKXNsExuGc8TTT5kPRTOpppViFW/eWAxLUA1J7mTiiElKNJ1QvrfutAgubHk6eP90szmZ1SCZyaCa64Dykp5iSi4LIhg=,iv:2lNlbUfkuWMltpu/hdAvd/dD2VI6Elcn2+VpX3Reql0=,tag:2hIzESx4NThdT+sImEm4lQ==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
