# secret to test if the encryption/decryption works with fluxcd.
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:Rpo5Kk9Sb3Qgk1M=,iv:eWtNGmD6c3G9OsMK8xsrtjPS0UBJzymvRAi2Z1394FM=,tag:E/dSMqG+7db1njAwrF9SCA==,type:str]
    EMAIL: ENC[AES256_GCM,data:GIsmbFbTDnfXvgNzVdwIaL5VrD/U8vUwkaA=,iv:desAaFZsoJi3K8y/S6vBGSgdyK78byI2TP3Ei6PSw8o=,tag:FUwUBpzYXhjIyNI8yeygtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByY3dKTjM0cS8zbXpKc1kv
            SURDSnkwL0JUZ1h1THp3MUZjVFZPZjhFekN3Clg3OVo3MFhiWGlMVVM3ZWhwdnh0
            Y2RmK2NWVnVsNHlMZzJnVGdmdUdacVUKLS0tIEtUcVBZZWs5UzN0V1o1VWYxL0xT
            Y1htM0xwdFU3YWlPV1A4SExGNVAyU3MKTmbK169n2WL4mzc9vOBfE65az8gvSATv
            YEz5lUBXJwl9rvNeI47e6N4Q4E7N6CknfPPqerx4pJZ/PK9PRx+0PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-05T13:14:14Z"
    mac: ENC[AES256_GCM,data:TVd6svBWM7Chcb6LSo8VYTdw+n2ut0mFMQFSYmTZO2f4T9vL7op8CLSesNoSowSbxAs/VAXVEOxZlw+xv+qINfGyAHJRmTHKLIaM0fnTNz+aFtL2oNEDqai0rCwf0H3iga0LpYEMDnaA7uIiR11iOZCJ/uSm6AHBjXe6PtJ9F+w=,iv:/rogeVAzfUvss+TKkt+nHU59FOhpLIUhK2FvpgQQP7U=,tag:jeODddVPvlmiSwtFFvP+bA==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
