# secret to test if the encryption/decryption works with fluxcd.
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:j1c2OIOc10oJuDM=,iv:xRpGp7Sab6E1kCx/7jKLUwaBpAQ7wX60sNsM5Z6dGIg=,tag:bNBj34jV19z0d77SwbarzA==,type:str]
    EMAIL: ENC[AES256_GCM,data:LBZo8pIbfnv3yC2JGs1QLSytIPt4DnQPSuA=,iv:AuXMthHDuCTAKZDdtUenNrqor60NsvXH0EI+Syiy1A4=,tag:Xbcb7VHN5ry2/W1kW1gLrw==,type:str]
    HOST_TRAEFIK: ENC[AES256_GCM,data:B+9FI2lMBA==,iv:ekYfG6fvMtn3Ig4eHX6epaB2QBldcBKKb0zDMVZ5JRA=,tag:pUtsPLw+R0rHdqp1a2p2xg==,type:str]
    HOST_HOMEPAGE: ENC[AES256_GCM,data:4ht85eC+js4=,iv:aY+TTJuwCyOzN6kudM/lNNNJ7qUGmwAGM101tQOsZvs=,tag:o619ozKYZVW2bKSPc5PVoQ==,type:str]
    HOST_PROMETHEUS: ENC[AES256_GCM,data:Nyjw3h01sbuODw==,iv:V35AHSvRmIM9MkWDPduR+QFW+slPKj08I+JSXGYjzxo=,tag:Jegk2HXWAjRxf1liERmw1A==,type:str]
    HOST_GRAFANA: ENC[AES256_GCM,data:6sHavOBWBw==,iv:SEnSfU3SzxzhF88vu9PG82f/T2jeDWzodBDuN1serQ8=,tag:l7tbg6c+oZQ5zu90/EMdrw==,type:str]
    HOST_ALERTS: ENC[AES256_GCM,data:kk/b4OOM,iv:ze45Dn05Jq8FXXMxD3d1cBOvUOApSNNrmT+AIbK3RUQ=,tag:57vtMcq1Z1rE2ivDRTcLcQ==,type:str]
    GRAFANA_USERNAME: ENC[AES256_GCM,data:cy0R3cntLA==,iv:+iiZ5hyMZIBDkZm3Su/0P1rcCYKZiNPMGEqhRxXoah0=,tag:1h8Er9E3/SutfQ3LzEuFbw==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:UydnqFJHwA==,iv:AW8qDf1z1FByTY5VKIfL1cRG9eo/Cbm7EpqqQ5Gr0PQ=,tag:v4v5QvwqiqIAYX09Q6kc7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBab3JPcFlKOHVZb1drV2Yv
            R0V3bTJMOGdjNDJraUROaDE3QnVicysvS0R3CmpHaE9uL3RjeWliUjJVK3dVcEl3
            alRxY0RvdDg1cWp3Q2xJNER6OU9QYTgKLS0tIC9GMTFXTEp5Ykw5NzJoaTlVeXlU
            YVc1VCs0R3I4VnUvTVdKVXptMkExTkEKWdKtGX/jfLdNoBBlxXarFB6wArypXa/g
            b9ebz4osXzQWuuCOY8D+ds0Ow5DaIAxDjqi+h1fshmYTqcgH3nOruw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-07T15:16:53Z"
    mac: ENC[AES256_GCM,data:VDt4SuGnHiSwJGNmBBpTWg3o/JjXixCbwlnKQluhioOOaj4brhNLRYggSc6LyS376v/MnUrNagbjnL5HmSYKqa7/LZa8PKCamY+lHFQF8U+Er/qOHlP+Swokvh26IRL1+QHF6vQjBTf/lC8p2K8TkOEYllzdCRv0CMsnMT03OtU=,iv:ezG2zjs+h4TbrcmeYEIvRhUKWVmDcyEQCKV1oxYzG9c=,tag:xnJOKeEQSIMysSE61jc5Sw==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
