---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr.${DOMAIN}
  namespace: media
spec:
  secretName: prowlarr.${DOMAIN}
  dnsNames:
    - ${HOST_PROWLARR}.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
