---
apiVersion: v1
kind: Service
metadata:
  name: test-khc-node-exporter   # service name
  namespace: monitoring
  annotations:
    tailscale.com/tailnet-ip: ${TAILSCALE_TEST_NODE_EXPORTER_IP}
spec:
  externalName: placeholder   # any value - will be overwritten by operator
  type: ExternalName
