---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 10m0s
  values:
    # Operator oauth credentials. If set a Kubernetes Secret with the provided
    # values will be created in the operator namespace. If unset a Secret named
    # operator-oauth must be precreated or oauthSecretVolume needs to be adjusted.
    # This block will be overridden by oauthSecretVolume, if set.
    oauth:
      clientId: ${TAILSCALE_CLIENTID}
      clientSecret: ${TAILSCALE_CLIENTSECRET}
    operatorConfig:
      # ACL tag that operator will be tagged with. Operator must be made owner of
      # these tags
      # https://tailscale.com/kb/1236/kubernetes-operator/?q=operator#setting-up-the-kubernetes-operator
      # Multiple tags are defined as array items and passed to the operator as a comma-separated string
      defaultTags:
        - "tag:k8s-operator"
        - "tag:test-k8s-operator"
    # proxyConfig contains configuraton that will be applied to any ingress/egress
    # proxies created by the operator.
    # https://tailscale.com/kb/1439/kubernetes-operator-cluster-ingress
    # https://tailscale.com/kb/1438/kubernetes-operator-cluster-egress
    # Note that this section contains only a few global configuration options and
    # will not be updated with more configuration options in the future.
    # If you need more configuration options, take a look at ProxyClass:
    # https://tailscale.com/kb/1445/kubernetes-operator-customization#cluster-resource-customization-using-proxyclass-custom-resource
    proxyConfig:
      defaultTags: ${TAILSCALE_PROXY_TAG}
