apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-vol-claim
spec:
  storageClassName: longhorn-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
