---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana.${DOMAIN}
  namespace: monitoring
spec:
  secretName: grafana.${DOMAIN}
  dnsNames:
    - ${HOST_GRAFANA}.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
