---
- name: Oh My Posh
  hosts: servers
  # connection: local
  # remote_user: root

  tasks:
    - name: Install unzip
      apt:
        name: unzip
        update_cache: true

    - name: Download Oh My Posh installer
      get_url:
        url: https://ohmyposh.dev/install.sh
        dest: /home/ghimele/oh-my-posh-install.sh
        mode: '0755'

    - name: Install Oh My Posh
      shell: |
        bash /home/ghimele/oh-my-posh-install.sh -d /usr/local/bin
      args:
        creates: /usr/local/bin/oh-my-posh

    - name: Check if CascadiaCode font is already installed
      shell: |
        fc-list | grep -i "CascadiaCode"
      register: cascadia_font_check
      changed_when: false
      ignore_errors: true

    - name: Install CascadiaCode font
      shell: |
        oh-my-posh font install CascadiaCode
      args:
        creates: /usr/share/fonts/truetype/CascadiaCode/CascadiaCode.ttf
      when:
        - cascadia_font_check.rc != 0
        - cascadia_font_check.stdout == ""

    - name: Create Theme folder if it doesn't exist
      file:
        path: /home/ghimele/.posh-themes
        state: directory
        mode: '0755'

    - name: Download the ghimele theme
      get_url:
        url: https://raw.githubusercontent.com/ghimele/shell-config/main/oh-my-posh-theme/ghimele.omp.json
        dest: /home/ghimele/.posh-themes/ghimele.omp.json
        mode: '0644'

    - name: Check if .profile contains already the theme
      ansible.builtin.lineinfile:
        path: /home/ghimele/.profile
        line: 'eval "$(oh-my-posh init bash --config ./.posh-themes/ghimele.omp.json)"'
        state: present
        insertafter: EOF
      check_mode: yes
      register: theme_check
      ignore_errors: true

    # - debug:
    #     msg: "{{ theme_check }}"

    - name: Ensure the bash prompt uses the ghimele theme
      ansible.builtin.lineinfile:
        path: /home/ghimele/.profile
        line: 'eval "$(oh-my-posh init bash --config ./.posh-themes/ghimele.omp.json)"'
        state: present
        insertafter: EOF

    - name: Remove Oh My Posh installer
      ansible.builtin.file:
        path: /home/ghimele/oh-my-posh-install.sh
        state: absent
