---
- name: ensure fonts directory
  file:
    path: "/usr/share/fonts/"
    state: directory

- name: Cascadia exists
  shell: "ls /usr/share/fonts/caskaydiacove*"
  register: caskaydia_exists
  ignore_errors: true

- name: Download Cascadia
  when: caskaydia_exists is failed
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/CascadiaCode.zip
    dest: "/usr/share/fonts/"
    remote_src: yes
