---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: longhorn
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    defaultSettings:
      defaultDataPath: /mnt/longhorn-data/
      # -- Percentage of disk space that is not allocated to the default disk on each new Longhorn node.
      storageReservedPercentageForDefaultDisk: 0
