---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant
  namespace: home-automation
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: "https://${HOST_HOME_ASSISTANT}.${DOMAIN}"
    gethomepage.dev/description: "Open source home automation"
    gethomepage.dev/group: "Home Automation"
    gethomepage.dev/icon: home-assistant.png
    gethomepage.dev/app: "home-assistant"  # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: "Home Asssistant"
spec:
  entryPoints:
    - websecure
  tls:
    secretName: homeassistant.${DOMAIN}
  routes:
    - kind: Rule
      match: Host(`${HOST_HOME_ASSISTANT}.${DOMAIN}`)
      middlewares:
        - name: security-header
          namespace: traefik
      services:
        - name: home-assistant
          kind: Service
          namespace: home-automation
          port: 8123
