---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-photos
  namespace: nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: ${STORAGE_NFS_SERVER}
  share: ${STORAGENFS_PHOTO_PATH}
  subDir: Photos
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4
  - hard
