---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zerobyte.${DOMAIN}
  namespace: nas
spec:
  secretName: zerobyte.${DOMAIN}
  dnsNames:
    - ${HOST_ZEROBYTE}.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
