---
- name: Add Brave GPG key
  ansible.builtin.apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
    state: present

- name: Add Brave repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
    state: present

- name: Install Brave
  ansible.builtin.apt:
    name: brave-browser
    state: present
    update_cache: true
