---
- name: Install System Packages
  become: true
  become_user: root
  apt:
    name:
      - curl
      - wget
      - git
      - htop
      - unzip
      - age
      - yamllint
      - ansible-lint
    update_cache: true
