---

- name: Get latest kubectl version
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: kubectl_version
  changed_when: false

- name: Check installed kubectl version (if any)
  ansible.builtin.command: kubectl version --client=true --output=yaml
  register: kubectl_installed
  failed_when: false
  changed_when: false

- name: Parse installed version
  ansible.builtin.set_fact:
    kubectl_installed_version: "{{ (kubectl_installed.stdout | from_yaml).clientVersion.gitVersion
                                   if kubectl_installed.rc == 0 else 'none' }}"

- name: Download kubectl binary if not latest
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_version.content | trim }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'
  when: kubectl_installed_version != (kubectl_version.content | trim)

- name: Verify kubectl installation
  ansible.builtin.command: kubectl version --client=true --output=yaml
  register: kubectl_check
  changed_when: false
  failed_when: kubectl_check.rc != 0

- name: Display kubectl version
  ansible.builtin.debug:
    msg: "kubectl version installed: {{ (kubectl_check.stdout | from_yaml).clientVersion.gitVersion }}"
