---
- name: Install System Packages
  become: true
  become_user: root
  apt:
    name:
      - curl
      - htop
      - unzip
      - lvm2
      - jq
      - nfs-common
      - open-iscsi
      - cryptsetup
      - dmsetup
      - lvm2
      - age
    update_cache: true
