apiVersion: v1
kind: Secret
metadata:
    name: oidc-secret
    namespace: traefik
type: Opaque
stringData:
    pluginSecret: ENC[AES256_GCM,data:MC0gMkDjrWckR/tnIHgvZZ3awrmCRv58uPFuoUg7Pi0aJ4iw0NZdSMn+qhk=,iv:hbymCgVa0dVehYDTiFP+imTRSkPgeL7K7p1vQrbmP0s=,tag:PWGWJU/s3dt2bp1ZsZhxhg==,type:str]
    providerUrl: ENC[AES256_GCM,data:uVUAs3JWuhhWDIJKt5jW7rZthqgTrw==,iv:LGeNsH3Rn2cjeeMzkVTkbqCc/HQTLJRswjgya0aUTEM=,tag:VENkkRBI/urEq7xZr5Zeuw==,type:str]
    providerClientId: ENC[AES256_GCM,data:HHD6mK4uTVDUxBmNfleSfOACkvBq515llEg/5VUPw6qyF8eN,iv:sKEivIo8DUOrO03lay0i67HQncRKgNq6U4yhklaZZXc=,tag:WVCA84zd3RzpqH7+XgrCsQ==,type:str]
    providerClientSecret: ENC[AES256_GCM,data:ckD6FwpP8VdpwX4nEwRN323Qz4l1VE/bm6KbBQI2J2I=,iv:dR+5qbaCRviqpnQt3sI7npqpc+wHbvoCGVcxb0METcA=,tag:DWhTIZNF65LiifKAWlUGBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RjQ3V3dTRkY2ditnb1BZ
            clhLQzdCVlRwRjA4ckV0dUdyczY5c3lRaTM0CjU4QUdlSGdRbzBEZUJFQUhQZlFU
            NUVHd0NETXdQU0huYnRRd0ZCeUlhYnMKLS0tIEpQWHlnSmdRY3JuVEZOdGIvUGZC
            TExsYW5jYjhmMXdpWTR3OEZQNWxJdVUKwFeKU7TukgKlSpeus3rNxSULYki0LhuF
            JNIypeQtx0as8WzdOf76PQ4mfcJWYz3cMQ4tMMhfGp6kRHk8kGFLFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T20:23:44Z"
    mac: ENC[AES256_GCM,data:4d72o58YSBUNZC4lVLT4tzsiuBsGOe5eAYruQ2YFJUjwrx3bXxvUhx3wpPD3boDTYt+GXZTDO10b7a990jqSPacx+jVLbmeSHGa+Q8he39DxXuzQKoggmJj/7B+a9IX91on1HJsbqSihgulg02fymLgvordmHcX6LOR7M431JLY=,iv:iz05FdXjets3ya7vzRAeMBEP5pSruOkj+6mi1hHXzGM=,tag:gONGSBr93JG3CuRERAtzzw==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.10.2
