---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 10m0s
  values:
    global:
      # -- Toleration for nodes allowed to run user-deployed components such as Longhorn Manager, Longhorn UI, and Longhorn Driver Deployer.
      tolerations: []
      # -- Node selector for nodes allowed to run user-deployed components such as Longhorn Manager, Longhorn UI, and Longhorn Driver Deployer.
      nodeSelector:
        # We will install all the services on nodes labeled as storage:longhorn (the agent nodes)
        node-role.kubernetes.io/longhorn: ""
    persistence:
      # -- Setting that allows you to specify the default Longhorn StorageClass.
      defaultClass: true
      # -- Filesystem type of the default Longhorn StorageClass.
      defaultFsType: ext4
      # -- Replica count of the default Longhorn StorageClass.
      defaultClassReplicaCount: 3
    defaultSettings:
      defaultDataPath: /mnt/longhorn-data/
      # -- Percentage of disk space that is not allocated to the default disk on each new Longhorn node.
      storageReservedPercentageForDefaultDisk: "0"
    # -- Setting that allows you to update the default backupstore.
    defaultBackupStore:
      # -- Endpoint used to access the default backupstore. (Options: "NFS", "CIFS", "AWS", "GCP", "AZURE")
      backupTarget: ${LONGHORN_BACKUP_TARGET}
      # -- Name of the Kubernetes secret associated with the default backup target.
      backupTargetCredentialSecret: ~
      # -- Number of seconds that Longhorn waits before checking the default backupstore for new backups. The default value is "300". When the value is "0", polling is disabled.
      pollInterval: ~
    metrics:
      serviceMonitor:
        # -- Setting that allows the creation of a Prometheus ServiceMonitor resource for Longhorn Manager components.
        enabled: true
