---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 10m0s
  values:
    global:
      # -- Toleration for nodes allowed to run user-deployed components such as Longhorn Manager, Longhorn UI, and Longhorn Driver Deployer.
      tolerations: []
      # -- Node selector for nodes allowed to run user-deployed components such as Longhorn Manager, Longhorn UI, and Longhorn Driver Deployer.
      nodeSelector:
      # storage: "longhorn"
    defaultSettings:
      defaultDataPath: /mnt/longhorn-data/
      # -- Percentage of disk space that is not allocated to the default disk on each new Longhorn node.
      storageReservedPercentageForDefaultDisk: 0
    longhornManager:
      log:
        # -- Format of Longhorn Manager logs. (Options: "plain", "json")
        format: plain
      # -- PriorityClass for Longhorn Manager.
      priorityClass: defaultPriorityClassNameRef
      # -- Toleration for Longhorn Manager on nodes allowed to run Longhorn Manager.
      # tolerations: []
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
