---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 10m0s
  values:
    global:
      # -- Toleration for nodes allowed to run user-deployed components such as Longhorn Manager, Longhorn UI, and Longhorn Driver Deployer.
      tolerations: []
      # -- Node selector for nodes allowed to run user-deployed components such as Longhorn Manager, Longhorn UI, and Longhorn Driver Deployer.
      nodeSelector:
        # We will install all the services on nodes labeled as storage:longhorn (the agent nodes)
        storage: "longhorn"
    persistence:
      # -- Setting that allows you to specify the default Longhorn StorageClass.
      defaultClass: true
      # -- Filesystem type of the default Longhorn StorageClass.
      defaultFsType: ext4
      # -- Replica count of the default Longhorn StorageClass.
      defaultClassReplicaCount: 3
    defaultSettings:
      defaultDataPath: /mnt/longhorn-data/
      # -- Percentage of disk space that is not allocated to the default disk on each new Longhorn node.
      storageReservedPercentageForDefaultDisk: 0
