---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smtp-gotify.${DOMAIN}
  namespace: cnpg-db
spec:
  secretName: smtp-gotify.${DOMAIN}
  dnsNames:
    - smtp-gotify.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
