# secret to manage the cloudflare api token used by cert-manager to generate a certificate.
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: kube-system
data:
    api-token: ENC[AES256_GCM,data:vHAxtqMYDWvY0AJe+Ka2+A6XVmlH2FI8iEdgLu8/WnkMv8j1uyszFA==,iv:yrqcwP70QbucQik/L4i/jjYaQCxack5l3+v1NIVilj4=,tag:AwT7qubrqZSgsTR6A3x5+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmK1Y1S2ZTTkxDTFluQk9H
            c211bzhKN3M3Ty9wVjJXOWU0MWhNN2dzWVEwCktSSGt3dkliRVpoTTBZc2t1M0M1
            VW1lWTNWdFpWRmlkRnlneGszZW96WlUKLS0tIEdDaDk5MklKMm1wNnpLemV6K1lL
            VG5zMEpjWGk3ZWdTcldMc09LTEM2MmMKaiTkC06DzAzWrf/XGh0xYxH/dxXYkY70
            R+tP8K4irTEsqNGpRu29OnwDnGoC6S86rTyCbHivSswedZEie/FXAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-07T07:14:26Z"
    mac: ENC[AES256_GCM,data:X4hw8hkqyH07a1Ph0zzio1Ojmt77QY480l4NptGuSE2dwguG+uNLUpX/gezlRKB3/z4w+DGJgqVs5rn/XTIHpWSEpnjkBH3BqDt3SDzZUlthHTDRG0TXFMMGd/F4kLJyAz5IW4IUMJPUbRa3ZHj7ER+Ppu3Z+BsoyHR4YQWrTfA=,iv:F/k5FyDXzsPdqzEMPv6B1b/6C8ORd1NBUyZJ9zF/uIM=,tag:aZpftvxH/Dwq+wK9zevVGA==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
