# secret to manage the cloudflare api token used by cert-manager to generate a certificate.
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
data:
    api-token: ENC[AES256_GCM,data:Wo0t8nIw6vgBvoCDfZZ+HO+Juo+GDJ9+XEXzondvB40kdciHWpt/UQ==,iv:jANx3tuhHiErDmVTWVH64WJgFvBpqIwmeQ6690rT0lY=,tag:1YPiy1DFE0RA0pNg6he+eg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNktQWTVEOGlRemI2cDVX
            RDdJay9HTStLWmJqSFZERytXVU1ZZmdtTEJJCkpvSjVBV0dUV0ozS1dmZWMyVXpa
            eS9JQ2EzN1lmcmZjS2F2M01DTXhYUTAKLS0tIERBdHdBRnprMThVckJPd2xZODV2
            cXF3NW1rblNPc3BRY1FFbG1DaDZ6cG8KIA4lBZ4n/JTq0qDLsT5VOIQBc0GWpuBi
            upE1UuuvSKvMvOyXgF4DSyNR8aTgZDJcZtZ7eEunp7LYOfEH8ixa+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-07T07:03:12Z"
    mac: ENC[AES256_GCM,data:foqsSp0BnwLJFFEZq7PbmrnhuM4kXG+X1lKaEbj7RZkp9Tgl5kz43/5Hn2RcqUQcihOo60+JPjX/A4qIKDriatRVPbUK6uU6UsB2b6j6ag3bTThAbzELuoBazgTQuTLAPOD5rHqPU1D+1RF6w0XnugwWcW7Uxoq8fWe7cUxnLpE=,iv:Fqp6/GE1vl7U2DeGoy7Cmo2VzvS029dzw/XA98xGcRM=,tag:BSQ+Ji9S2EqSHoWhYRbkwA==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
