# secret to manage the cloudflare api token used by cert-manager to generate a certificate.
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:ujMJnknI5tgy9uK/HpDBNUcuINEwkCvR0l71bzLi1rjyU1itQDU1Mw==,iv:am1g3CzZjY63qBmax+uHT0FCzw5CHfCiMKvEoxeJfxY=,tag:qkLU7nq1/uRqDNMr8pcGDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMT3VrNEtrZkwzVjdWOG80
            bTl3TWZtckhFcmp0SERBdGI2V2tpZjBJWFg0Cll2L2dST1BFczdFak9QSUltS3kr
            ZnFRb0VBazY2SXEzMjZYeVFFemhsdDAKLS0tIGNpcDhlbENCQXBWdUtuTVpGVjR5
            ZHJ5b2c5anAzUXFPcWZ1aEYrb2ZQNXcKJWS4ih08JXRUpVgzzh86E+gslEhswtMy
            tU3/deeytywEQkd5+jfaWZSVlxQmhVxqrvr7o9XN71qohGzsfiwTHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-07T07:24:07Z"
    mac: ENC[AES256_GCM,data:y7HvLFRDfeppZhWuRFQo8+Pvqz5ufES/rm8HsRH1zh5RnfyzuMgN4cxsX/TXKYR4deVVAum4LO45tXjDFi1nMoLttbcme/lFYHpYvVl06L4gYflwiiMFJMcnjBz0mJa+28ciQ+ZEErptmwYAJVEnTZl34GZeO7e1oxpuIsLwnTk=,iv:99ioXUBaVKH1+Wen5N8cqTXkv48+6Y4OxlYiYH8VUoQ=,tag:P7+DdK61RzHQRH+ygxejVg==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
