# secret to manage the cloudflare api token used by cert-manager to generate a certificate.
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:bZVauqmB8N/++Zc3FbRNkxDV+ZCTLO6z0vuspa5wEm/6XQwUj2jJ1w==,iv:UsJmpeSLnjHvE9nVUoB9cJ+o4aCDXjPX2D2AgDV0nCc=,tag:kECutszBpo1bPYwNDQ+LJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUjh4RFVZc3dKaFFPMWU4
            OUcyZlpRdXRscENCaTRxUGV4QzlVZGV3aUZJCkVtaXBzL2RnNml2ZzdFVmpVK2F1
            aVFEblk0TnhuWXZWWVJURGRqVmtlb3cKLS0tIHVoZ3FHbVE2dlE2MVFDT1VpTVZh
            RjBSZXJnbW9nc0F6V293d0x3RVZXMkUK55P69lLUnBJfw63V7ASjASgEAUsLZLBC
            OVFFDFjNO2MpoovbdaCRsbLPNE6fff91NW4W68GXvbT3IXUKjUjo+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-05T13:42:45Z"
    mac: ENC[AES256_GCM,data:VkIKKeTCG3VqwQHPTyVvIRSN+Hg1kR5pMVcHfEIwM3MEsxOspIvaOiCe0D/DZtH0b26d2KtMwE16Q15CvpZ49HmQCh346v7quEnNA2DFPl5imdxo1osJ6pla0DKml4sMrzlaJadl+rsvIwV3Iem/hzUGYjRgeWA6FJPhkWexaEU=,iv:CFE4W1EZeDf8KRhy97nUtR081hYJSj0ELK0FxpjwYOU=,tag:c6kcK9hA5aUFaA7ZKI006g==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
