---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: loki
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`${HOST_LOKI}.${DOMAIN}`)
      services:
        - kind: Service
          name: loki
          namespace: monitoring
          port: 3100
  tls:
    secretName: loki.${DOMAIN_INTERNAL}
