---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m0s
  values:
    loki:
      singleBinary:
        persistence:
          storageClass: longhorn
