---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
  namespace: security
spec:
  interval: 10m
  values:
    config:
      APP_URL: https://${HOST_POCKETID}.${DOMAIN}
      TRUST_PROXY: "true"
      ENCRYPTION_KEY: ${POCKETID_ENCRYPTION_KEY}
      PUID: 1000
      PGID: 1000
      DB_CONNECTION_STRING : postgres://pocketid:${POCKETID_DB_PASSWORD}@postgres-cluster-rw.cnpg-db.svc.cluster.local:5432/pocketid

    persistence:
      # -- enable persistence when true
      enabled: true
      # -- default storage size
      size: 1Gi
      # -- accessMode
      accessMode: ReadWriteOnce
      # -- actual storageClass
      storageClass: longhorn

    service:
      type: ClusterIP
      port: 1411
      annotations:
       gatus.io/monitor: "true"
       gatus.home-operations.com/endpoint: |
         group: "infrastructure"
         url: http://pocket-id.infrastructure.svc.cluster.local:1411/
         conditions:
           - "[STATUS] == 200"
           - "[RESPONSE_TIME] < 1000"
