---
resources:
  - ./monitoring-namespace.yaml
  - ./security-namespace.yaml
  - ./metallb/
  - ./cert-manager/
  - ./traefik/
  - ./headlamp
  - ./system-upgrade/
  - ./longhorn/
  - ./tailscale/
  - ./storage/
  #- ./pocket-id/
