---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
  annotations:
    gethomepage.dev/href: "https://${HOST_TRAEFIK}.${DOMAIN}"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Traefik Dashboard
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: traefik.png
    gethomepage.dev/app: traefik # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: Traefik
    gethomepage.dev/widget.type: "traefik"
    gethomepage.dev/widget.url: "https://${HOST_TRAEFIK}.${DOMAIN}"
    gethomepage.dev/pod-selector: ""
    gethomepage.dev/weight: 10  # optional
    gethomepage.dev/instance: "public"  # optional
spec:
  entryPoints:
    - websecure
  tls:
    secretName: traefik.${DOMAIN}
  routes:
    - kind: Rule
      match: Host(`${HOST_TRAEFIK}.${DOMAIN}`)
      services:
        - name: api@internal
          kind: TraefikService
    - kind: Rule
      match: Host(`${HOST_TRAEFIK}.${DOMAIN}`) &&  PathPrefix("/api")
      services:
        - name: api@internal
          kind: TraefikService
