---

- name: local_server
  hosts: localhost
  tasks:
    - import_tasks: tasks/linux/server_packages.yaml
      tags:
        - server
    - import_tasks: tasks/linux/fonts.yaml
      tags:
        - fonts
    - import_tasks: tasks/linux/oh-my-posh.yaml
      tags:
        - terminal
    - import_tasks: tasks/linux/sops_localhost.yaml
      tags:
        - server
    - import_tasks: tasks/linux/cache-folder.yaml
      tags:
        - server
