---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
  namespace: media
spec:
  entryPoints:
    - websecure
  tls:
    secretName: jellyfin.${DOMAIN}
  routes:
    - kind: Rule
      match: Host(`${HOST_JELLYFIN}.${DOMAIN}`)
      services:
        - name: jellyfin
          kind: Service
          namespace: media
          port: 8096
