---
# jellyfin release
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  values:
    persistence:
      media:
        storageClass: nfs-media
        ## -- Use an existing PVC for this mount
        existingClaim: media-pvc

    # -- Node selector for pod scheduling.
    nodeSelector:
      # We will install all the services on nodes labeled as storage:NFS (the agent nodes)
      node-role.kubernetes.io/nfs: ""
