---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
configMapGenerator:
  - name: grafana-datasource-loki
    files:
      - loki.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana-datasource: 'true'
