---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-cluster.${DOMAIN}
  namespace: cnpg-db
spec:
  secretName: postgres-cluster.${DOMAIN}
  dnsNames:
    - postgres-cluster.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
