---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: clusterdb.${DOMAIN}
  namespace: clusterdb
spec:
  secretName: clusterdb.${DOMAIN}
  dnsNames:
    - clusterdb.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
