apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: db-credentials
    namespace: cnpg-db
stringData:
    username: ENC[AES256_GCM,data:F88HEuGZEMo=,iv:dk1COubAlFwUVqePWRcp03n/eiKwSaN6iHPgM1q4ShE=,tag:e5BGwytNoA23Q8/6gvwy3A==,type:str]
    password: ENC[AES256_GCM,data:wqgm6fi475oQNoE=,iv:dimOCVIl1dK5ytPWhe0SEOd7a2E1lUCRuLnaI9S714w=,tag:SpHcuJkI69qKC4V6NkL/5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UnRkejdBMFUvM0lUdDRF
            Q3IrOWFsUHZNaWZ4N2phM2dyekZuWXVzK1JvCnh5RnVNOVY4a2VNUUVMbU5jdXFN
            VGI0alF6QnJXSy8yc0g0bVB5a2QzejAKLS0tIE1wRlBxeUNjWng3MGplbmt2UFIv
            aE5oOVNaZVBjblpUTjdpWm5pQ3dNbzQKWyuKUgrHMJG73sb4uVTEf0wbCiL3f9k0
            YJw6NBwjSduYqz9UEevpyVcGlYueZ2B/AoaC0rmpiXQ+fMyschUCkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-25T14:38:26Z"
    mac: ENC[AES256_GCM,data:YlGz07eSELeVXe7oCXtUzEk9v5/FBf3PXq4JzwTq9zJXo6bGO2+HBaK5m5hXkCewt8nQwqJXga3iLpIQHHgvyvEOcldD6CsWlhmGEiGYGbIffr23ddG+dJLKq94JFi46c13nC5gcsJi6IwGaZ21g2mDgBHe4PSzySmygO0msnNw=,iv:oPHb1rXA6AhizzVB+1odze57EBmSDV4A6GPuX39yV8Q=,tag:KVTzx+l7wZ2pIqnSvflHKQ==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
