apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: db-credentials
    namespace: clusterdb
stringData:
    username: ENC[AES256_GCM,data:F88HEuGZEMo=,iv:dk1COubAlFwUVqePWRcp03n/eiKwSaN6iHPgM1q4ShE=,tag:e5BGwytNoA23Q8/6gvwy3A==,type:str]
    password: ENC[AES256_GCM,data:wqgm6fi475oQNoE=,iv:dimOCVIl1dK5ytPWhe0SEOd7a2E1lUCRuLnaI9S714w=,tag:SpHcuJkI69qKC4V6NkL/5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UnRkejdBMFUvM0lUdDRF
            Q3IrOWFsUHZNaWZ4N2phM2dyekZuWXVzK1JvCnh5RnVNOVY4a2VNUUVMbU5jdXFN
            VGI0alF6QnJXSy8yc0g0bVB5a2QzejAKLS0tIE1wRlBxeUNjWng3MGplbmt2UFIv
            aE5oOVNaZVBjblpUTjdpWm5pQ3dNbzQKWyuKUgrHMJG73sb4uVTEf0wbCiL3f9k0
            YJw6NBwjSduYqz9UEevpyVcGlYueZ2B/AoaC0rmpiXQ+fMyschUCkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T18:51:51Z"
    mac: ENC[AES256_GCM,data:c4YsMSlSj9B7j3/MJyFsQ9K5x4P1uvvZPlTPUc4VtVtopGsquWfFNxMHb8IzqjKysn5Qr6z8YbOyN+0zxN1hPbMT9zelTZvLZExWtiEjjsLzQotIt6FSdcsWLAXCMBTLIstWO8Iqw1wS3wOqINipX2TY3J5uOSNWGnbqf5yHXfM=,iv:fhHBVpB+CV0eGaM9BYydFlQXt85obycWJPEpGl2ZXBQ=,tag:1I5ptmSj05Sfn69YZ9Q0Ow==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
