apiVersion: v1
kind: Secret
metadata:
    name: db-secrets
    namespace: clusterdb
stringData:
    username: ENC[AES256_GCM,data:d8rDSlc5g0s=,iv:HPy6VtFND7NlRIGigsGwESUxfJ76UzucMgByD8SOejw=,tag:gxxd5yTcNtD4aD6Ti67MRQ==,type:str]
    password: ENC[AES256_GCM,data:a8nNTqmU7GbJ+vE=,iv:KF48eWg6MSBpviUd9JIbRoX+OnRsquiyqEuo6MPnH6o=,tag:Nerg0yMnw/AXsUtg7oB4fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUL1MwaFVpaVFvRFJxL2xO
            Y3E5bC9VMk04R2VkTDI2cXUyUXNDbFpkM1hRCmFwNGlSQnhyREJmMFU5WWR6RzRU
            S05HTVZBQmZ4SGJTNUhuM3U1U0VzbFUKLS0tIFlQSjBsNVQ5NnExRVc0UUtMUWVv
            R1Q1STU4dk9iUUtMd1VnbUtTWUNnT0EKTwNtcJs/uOkhjyzkCG/N8HlhxqPqPg6E
            vv7VFtHCkZ9P4z78U8BmF37OJg0gtRaLFzZ74HyGgkSop7x4d8JTXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T12:37:27Z"
    mac: ENC[AES256_GCM,data:hW1y1+4H3mycgDyeOIbzFH2QlE4aOa0DymtYn/If+7hdxnAUSOS+qwXGiwii+UX4ylmtrSPrHDX4QKvZPv0LrtQewHmRSo8mR8/2+AydB5AbP84MBB61hhEba6M73OHL+jTElmkWcQh97+cYRLSDGJM0WGSgPi0Fyu5kBkgwjsA=,iv:qyC0tpXXis6BfxsXkWGeqjaIPteP5+bfbM9mZKAiI/g=,tag:pKoBH1s07YfuyFDmHUT6JQ==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
