apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: db-secrets
    namespace: clusterdb
stringData:
    username: ENC[AES256_GCM,data:z4e5Vb/TefA=,iv:rq1nwuypDx6Dzh3I7Q5RpQzuDiWRQpLkveXy3rO7ZOw=,tag:R9j/w/d+bVdlLVRn6JpGlA==,type:str]
    password: ENC[AES256_GCM,data:uZarPmIpWcri6uQ=,iv:4ET9FVUFQYBV7LHdZf4h5PDgY3XWf0w6X9JUob4f2Bo=,tag:LhSshHBPOrq/tRTcUZ8T4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xv8cuqcr09e3845unmja9x5jct30q9rmgz7awjc6dwrnq5m79etsvkz2z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UzRsOUNRM3RpSnJHTVJZ
            aUFYbEk5cllhMVF4SEdGblhtdEtzM25ua0ZnCkljVDZpWHN1L3FSWUUxRTRoN2NT
            NTladXVCaDFlZGRaRDZRTFk5UXkxSVUKLS0tIHRLdktIbDRnWjMxWVJzS1B3dlp0
            ZUREU2lDdWwrcU1aWVZqQnBubXNscDgKpuKIIF6NCSNSAZMG53aR0nNJUT46Oows
            sBFpGXdiw1CAsreR9ZeWK5V9JZvGRZEv4ROg0nnPAOoZIqz3T+0cBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T13:22:04Z"
    mac: ENC[AES256_GCM,data:UzAZB0QlxwesEuwx6bLmgZSE05esvYbLK8qNwWXgSglisCHNgae80PvLE+BNjsFPrnN7pkf+WYZv7s4E86J8pBloKzoFJPXStWYRHpBwHg4ImDpFPVmo3Eu7gsCNTwz7ahKJ7+iu8yH7PL2E6tqZRP27jnh6FrnX/Njs9qu/OeQ=,iv:8Ukz9hMOaWWfcJqHKE2vhfvBddJzNWTw5aSpDNILNQo=,tag:jll1MiwScZzJdWJoI7I0KA==,type:str]
    pgp: []
    encrypted_regex: ^(user.*|pass.*|.*[Bb]earer.*|.*[Kk]ey|.*[Kk]eys|salt|sentry.*|.*[Tt]oken|data|stringData|match|href)$
    version: 3.9.0
