---
resources:
  - namespace.yaml
  - db-credentials.enc.yaml
  - postgres-cluster-gotify.enc.yaml
  - postgres-cluster-homeassistant.enc.yaml
  - longhorn-postgres-storage.yaml
  - postgres-cluster.yaml
  - certificate.yaml
  - ingress-route.yaml
  - gotify-db.yaml
  - homeassistant-db.yaml
