---
resources:
  - db-credentials.enc.yaml
  - postgres-cluster-gotify.enc.yaml
  - postgres-cluster-homeassistant.enc.yaml
  - postgres-cluster-wppm.enc.yaml
  - longhorn-postgres-storage.yaml
  - postgres-cluster.yaml
  # - ../../../base/cloudnative-pg/cluster
  - certificate.yaml
  - ingress-route.yaml
  - tablespaces.yaml
  # - roles.yaml

# patches:
#   - path: values.yaml
#     target:
#       kind: HelmRelease
