---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: cnpg-db
spec:
  description: "PostgreSQL Cluster"
  # imageName: ghcr.io/cloudnative-pg/postgresql:17.2
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.5
  # imagePullSecret is only required if the images are located in a private registry
  # imagePullSecrets:
  #   - name: private_registry_access
  instances: 3
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '1000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'
      max_slot_wal_keep_size: "2.5GB"
      pgaudit.log: "all, -misc"
      pgaudit.log_catalog: "off"
      pgaudit.log_parameter: "on"
      pgaudit.log_relation: "on"
    shared_preload_libraries:
      - "vchord.so"
    # synchronous:
    #   method: any
    #   number: 1
    #   dataDurability: required

  enableSuperuserAccess: true

  storage:
    storageClass: "longhorn-postgres-storage"
    size: 30Gi

  walStorage:
    storageClass: "longhorn-postgres-storage"
    size: 30Gi

  monitoring:
    enablePodMonitor: true

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
    tolerations:
      - key: node-role.kubernetes.io/postgres
        operator: Exists
        effect: NoSchedule
  managed:
    roles:
      - name: homeassistant
        ensure: present
        comment: HomeAssistant Role
        login: true
        superuser: false
        passwordSecret:
          name: postgres-cluster-homeassistant
      - name: gotify
        ensure: present
        comment: HomeAssistant Role
        login: true
        superuser: false
        passwordSecret:
          name: postgres-cluster-gotify
      - name: immich
        ensure: present
        comment: Immich Role
        login: true
        superuser: true
        passwordSecret:
          name: postgres-cluster-immich

  tablespaces:
    - name: homeassistant
      storage:
        size: 10Gi
        storageClass: "longhorn-postgres-storage"
    - name: gotify
      storage:
        size: 1Gi
        storageClass: "longhorn-postgres-storage"
    - name: immich
      storage:
        size: 10Gi
        storageClass: "longhorn-postgres-storage"
