---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: cnpg-db
spec:
  managed:
    roles:
      - name: homeassistant
        ensure: present
        comment: HomeAssistant Role
        login: true
        superuser: false
        passwordSecret:
          name: postgres-cluster-homeassistant
      - name: gotify
        ensure: present
        comment: HomeAssistant Role
        login: true
        superuser: false
        passwordSecret:
          name: postgres-cluster-gotify
      - name: wp_pm
        ensure: present
        comment: HomeAssistant Role
        login: true
        superuser: false
        passwordSecret:
          name: postgres-cluster-wp_pm
