---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: cnpg-db
spec:
  tablespaces:
    - name: homeassistant
      storage:
        size: 5Gi
        storageClass: "longhorn-postgres-storage"
    - name: gotify
      storage:
        size: 1Gi
        storageClass: "longhorn-postgres-storage"
    - name: wp_pm
      storage:
        size: 2Gi
        storageClass: "longhorn-postgres-storage"
