---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: longhorn
      version: 1.7.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
