---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: nfs-photos
