---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage.${DOMAIN}
  namespace: homepage
spec:
  secretName: homepage.${DOMAIN}
  dnsNames:
    - homepage.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
